### ISSUE TITLE
Manually setting RGB colors in Colorize (interactive) filter

### ISSUE THREAD

**Issue by narayaan** [dtschump/gmic-community#1]
Right now it is quite difficult to reprocude a fixed color (say rgb 118, 88, 88) in the palette. A way to manually enter preferred color codes would be a nice improvement in the colorize (interactive) filter.

**Comment by dtschump** [comment]
It is indeed not possible to select a color by values in the color selector widget.
To do so, it is recommended you create your own palette as a .gpl file, and specify it in the filter parameters instead.
