### ISSUE TITLE
wavelet decompose not reversible

### ISSUE THREAD

**Issue by orbisvicis** [dtschump/gmic-community#101]
Is this supposed to happen? This is the result after I recompose the wavelet decomposition:

* merge visible
* difference mode
* merge visible
* auto levels

![gmic wavelet decompose recompose](https://user-images.githubusercontent.com/730739/31050497-8a71967e-a619-11e7-83b2-4df53d21f292.png)

This is gimp in rgb uint8_t mode.

**Comment by dtschump** [comment]
That is not really surprising. From a numerical point of view, the wavelet decomposition is not perfectly reversible, you'll always loose a bit of precision as IEEE floats cannot store all possible floats with full precision. The auto-level makes the difference very clear, but what is the range of the difference ? 
If the max error is less than 4-5, I'd say everything is normal.

**Comment by orbisvicis** [comment]
Yeah, auto-levels maps 0-3 to 0-255, so looks good. By the way, do you know how to get a similar effect in a much more straightforward manner? Looks like banding both parallel and perpendicular to the gradients, each type of band being a different (primary) color and overlapping additively (or similar).

Can make some interesting effects like:

![logo light](https://user-images.githubusercontent.com/730739/31058857-ffcfb630-a6c8-11e7-8c36-0ce443dfbd8f.png)
