### ISSUE TITLE
Downloads Error out with 404

### ISSUE THREAD

**Issue by VikramN** [dtschump/gmic-community#102]
Download issues on the page - http://gmic.eu/download.shtml

Getting 404 for - 

Zart - http://gmic.eu/files/prerelease_windows/gmic_zart_win64.zip
Win64 -  http://gmic.eu/files/prerelease_windows/gmic_qt_win64.zip

**Comment by dtschump** [comment]
Thanks for reporting.
The build of these two G'MIC interfaces for Windows are not really well supported, so I've removed the links.
