### ISSUE TITLE
Download gmic for Krita : Impossible to unzip      

### ISSUE THREAD

**Issue by artweave** [dtschump/gmic-community#103]
Hi,
After 4 download, i can't install plugin for Krita
Error message:
gmic_krita_qt_win64.zip: Erreur de somme de contrôle dans gmic-krita-qt-2.0.4-win64\gmic_film_cluts.gmz. Le fichier est corrompu
gmic_krita_qt_win64.zip: L'archive est corrompue
Thank you

**Comment by dtschump** [comment]
Should be fixed now.
Alternatively, you may want to test the latest development version : http://gmic.eu/files/prerelease_windows/
