### ISSUE TITLE
gmic_libc.cpp: output format E_FORMAT_BYTE won't be set in the resulting image

### ISSUE THREAD

**Issue by boessu** [dtschump/gmic-community#108]
First things first I'm using G'MIC via Java JNA (see github). So maybe I missing here something I didn't saw.

If the _options->output_format is set to E_FORMAT_BYTE, the following code snipped will be executed:

>       if (_options && _options->interleave_output) {
>         img.permute_axes("CXYZ");
>       }
>       if (_options && _options->output_format == E_FORMAT_BYTE) {
>         gmic_image<unsigned char> img_tmp;
>         img_tmp = img;
>         _images[i].data = img_tmp._data;
>         img_tmp._is_shared = true;
>         img._is_shared = false;
>       } else {
>         _images[i].data = img._data;
>         img._is_shared = true;
>       }
> 
> 

However, what won't be set is _images[i]->format and _images[i]->interleave. So the outcome, if the data will be interleaved and / or set the format to byte is a _images[i] which claims to be still float and non-interleaved. That should be fixed, otherwise it's just a "guess" in the usage of the library what G'MIC really executed for the output images.

**Comment by tobybear** [comment]
I will look into it...

**Comment by tobybear** [comment]
It seems you are right, the two fields are not populated in the _images array for the output, probably since the options "output_format" and "interleave_output" let the developer define this globally. G'MIC always outputs as non-interleaved floats in the interface (unless it is forced by the above settings), so there is no guesswork as to what format the output is generated in. But I will add the setting to the output image fields nevertheless to avoid confusion.

**Comment by boessu** [comment]
Thanks for fixing that. I tramped exactly into that confusion trap. ;-)
I was not fully sure if that's always the case as the documentation of the interface has not a great length. But now I can make a workaround for that and clean-up the Java interface too. I'll add a Wiki page about the C interface if I find some time.

**Comment by tobybear** [comment]
I uploaded a fix, please test if the behaviour is now as expected

**Comment by boessu** [comment]
Only the 64 bit version was updated. The 32 is not. I guess the update had a different reason...

**Comment by dtschump** [comment]
I'm facing different issues with the packaging of G'MIC. I think these issues are minor, **but** I'm really running out of time to put my hands in this.

**Comment by boessu** [comment]
Fixed in release 2.1.9.
