### ISSUE TITLE
gmic_libc.cpp: One image name rules them all

### ISSUE THREAD

**Issue by boessu** [dtschump/gmic-community#109]
According to the source code, the only name which will be used for image naming is the last one provided in _images (line 99):
`std::strcpy(images_names[0], _images[i].name);`
On the other side in the resulting images, the only name which will be set is the name of the first image (line 139):
`std::strcpy(_images[i].name, images_names[0]);`

Of course this is also what I get as a result if I'm using the interface here.

So the workaround is to use numeric references. However it is not possible to use name references in scripts then, only numeric references. I would rather expect that the index `i` would be used instead of the `0`.

Since that's so specific coded that way, I'm not sure if that has a specific reason behind it. So it's maybe a question: Is there a reason that we don't use and don't get the name according to the image from the gmic library?

**Comment by tobybear** [comment]
Seems like a bug to me. That [0] index is most likely supposed to be [i], as you already wrote. I will make the change next week and do some tests, then upload a new file.

**Comment by tobybear** [comment]
I uploaded a fix, please test if the behaviour is now as expected

**Comment by boessu** [comment]
Sure, I can test that on Windows.
Is there a way to get a nightly build for that?

**Comment by boessu** [comment]
Fixed in release 2.1.9.
