### ISSUE TITLE
Focus not put on the filter tree

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic-community#11]
**Config:** G'MIC and G'MIC for GIMP 1.6.5.1 on Xubuntu 15.04

When I click on a filter inside the filter tree, for example *Array [faded]*:

![capture d ecran_2015-08-07_02-50-57](https://cloud.githubusercontent.com/assets/687082/9130422/887c0d1a-3cb0-11e5-8f63-91a560e00bef.png)

I would expect that the focus is put on it, so by using arrows up and down, I would move throw the tree (*Array [mirrored] / Array [random colors] / Array [random] / ...*) with the keyboard. It would be convenient: just keep an eye on the preview area and see results for browsed filters.

**Comment by dtschump** [comment]
Indeed, this is now fixed by commit : https://github.com/dtschump/gmic/commit/71fbf87038a7daebcab0563e16a8f4961846ba06

**Comment by jpfleury** [comment]
Good news. :-) Thanks a lot.
