### ISSUE TITLE
Arch linux, GIMP and gmic

### ISSUE THREAD

**Issue by Chawoosh** [dtschump/gmic-community#111]
GIMP 2.9 don't see new version of g'mic (old version from repo don't work with this GIPM). If I'm running gmic plugin from command string, I see error message
`./gmic_gimp_qt: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./gmic_gimp_qt)`

G'MIC is compiled with very old version of libcurl, I guess.

**Comment by dtschump** [comment]
Have you tried to compile the plug-in by yourself, or did you use pre-build binaries from the website ?
What kind of distro are you using ?

**Comment by Chawoosh** [comment]
I'm trying to use binary from site. Btw - binary from Arch repo works...
