### ISSUE TITLE
gmic_gimp_qt_win64 2.1.8 do not work on Gimp 2.9.8. GTK one do. Took me one hour to find out.

### ISSUE THREAD

**Issue by BanD11** [dtschump/gmic-community#115]
So, basicly, as title says, gmic_gimp_qt_win64 do not work on GIMP 2.9.8.  I've installed gmic_gimp_qt_win64 firstly in directory installer offered (%username%/.gimp.blablabla). GIMP launched with following mistakes:

> gmic_gimp_qt.exe
> The procedure entry point g_getenv could not be located In the dynamic Link Library C:\Program Files\GIMP 2.9\bin\libgimp-2.0-0.dll.
> 
> gmic_gimp_qt.exe
> The procedure entry point g_filename_from_utf8 could not be located In the dynamic Link Library C:\Program Files\GIMP 2.9\bin\libgimpconfig-2.0-0.dll.
> 
> 
> gmic_gimp_qt.exe
> The procedure entry point g_getenv could not be located In the dynamic Link Library C:\Program Files\GIMP 2.9\bin\libgimpcolor-2.0-0.dll.
> 
> gmic_gimp_qt.exe
> The procedure entry point g_dir_open could not be located In the dynamic Link Library C:\Program Files\GIMP 2.9\bin\libgimpbase-2.0-0.dll.

G'MIC didn't showed up in Effect. I reinstalled then  G'MIC in C:\Users\Username\AppData\Roaming\GIMP\2.9\plug-ins\gmic_gimp_qt\
C:\Users\Username\AppData\Roaming\GIMP\2.9\plug-ins\
C:\Program Files\GIMP 2.9\lib\gimp\2.0\plug-ins\gmic_gimp_qt\
C:\Program Files\GIMP 2.9\lib\gimp\2.0\plug-ins\
Nothing worked out. I reinstalled GIMP, deleted all instances of G'MIC, reinstalled it from zip, didn't help. Then i finded simular problem, solution was to copy DLL's with error to plugin directory. Tried, did not helped either. Now error text changed to 

> gmic_gimp_qt.exe
> The procedure entry point g_getenv could not be located In the dynamic Link Library C:\Program Files\GIMP 2.9\lib\gimp\2.0\plug-ins\gmic_gimp_qt\libgimp-2.0-0.dll.

At this i stopped and thinked a little. "If G'MIC try to find something in library and he can't, then maybe library has been updated and i should update G'MIC as well". I downloaded gmic_gimp_qt_win64 from prerelease catologue (which wasn't pre-release version, as it turns out). Then, at last, i downloaded gmic_gimp_gtk_win64.exe. Installed it. Removed all other versions. Launched GIMP.
It worked. After more than an hour of hard googling, it is finally working.

So, what the point of this story, you might ask? Well, there is even two.
First - if possible, update G'MIC to correspond to GIMP. If it isn't, then - 
Second - add a text to download page, noticing users of last GIMP versions about this problem.

Well, that's probably it. Would be glad to hear the end of story from you, developers!

**Comment by dtschump** [comment]
Hello, thanks for your report.
Just a little note though : the executable and installer provided on the G'MIC website has never meant to be compatible with the development version of GIMP, but only with the stable version (2.8.x).
It appears it was working somehow, but in any case, it was not optimal, as it was not handling the 16bits or 32bits new color spaces now managed in GIMP 2.9.
For GIMP 2.9.x, I would rather suggest you try one of the plug-in version specially compiled for 2.9 (thus managing higher color depths), I think samj and Partha's websites are good places to look for : 

Samj (in French) : http://samjcreations.blogspot.fr/
Partha : https://www.partha.com/

I honestly hope I'll be able to update my compilation environment on Windows, when GIMP 2.10 stable will be out, but I'm not even sure I'll be able to do that soon.

**Comment by sylale** [comment]
Bonjour,
You can try a test with Gimp 2.9.9 compiled today (20180105) :
[http://samjcreations.blogspot.ca/2018/01/version-de-developpement-gimp-299_5.html](http://samjcreations.blogspot.ca/2018/01/version-de-developpement-gimp-299_5.html)
Good luck!
