### ISSUE TITLE
Select color layer in "Colorize lineart" filter with mode "Auto-clean bottom color layer"

### ISSUE THREAD

**Issue by RebornSage** [dtschump/gmic-community#117]
Hello

I'm trying to follow this tutorial on the "Colorize lineart" filter (https://www.youtube.com/watch?v=Bvi7p3sRIJM) with Krita 3.3.3 and gmic 2.1.9
The "Generate random-colors layer" mode works fine. However, I cannot find a way to select the bottom color layer for the "Auto-clean bottom color layer" mode. Am I missing something?
![gmic](https://user-images.githubusercontent.com/34380800/35196482-dcca8eb4-fed2-11e7-8c90-aa98d8874476.jpg)

**Comment by dtschump** [comment]
You have to change the 'Input layers' mode in the 'Input/Output options' below the filter parameters.
In your screenshot, these parameters have been hidden, as you have moved the bottom slider to hide them (intentionally or not!).

**Comment by RebornSage** [comment]
Thanks, I found it! I am pretty sure it was hidden since I started the plugin the first time and that's why I haven't seen it.
