### ISSUE TITLE
G'MIC online doesn't work

### ISSUE THREAD

**Issue by nicaogr** [dtschump/gmic-community#119]
Hi,

I tried to use [G'MIC online](https://gmicol.greyc.fr/index.php) on Firefox and Chrome (on Ubuntu) but it doesn't seem to work at all. 
I just tried to extract contours of an jpg image with a size around 600*600 pixels.

Best,

**Comment by dtschump** [comment]
Thanks for reporting. The service has been restarted and should now work as expected.

**Comment by nicaogr** [comment]
Thanks.
