### ISSUE TITLE
Broken links "Filter explained here"

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic-community#12]
There are a few links *Filter explained here* that are broken:

- *Artistic / Photoillustration*
- *Colors / Metallic look*
- *Colors / Vintage style*
- *Details / Dynamic range increase*
- *Details / Mask creator*
- *Details / Portrait retouching*
- *Stereoscopic 3d / 3d conversion*
- *Stereoscopic 3d / 3d video conversion*
- *Stereoscopic 3d / Lenticular print*
- *Stereoscopic 3d / Single image stereogram*
- *Testing / Naggobot / Gmic structure tensors*
- *Testing / Tom keil / Dof manipulation*

**Comment by jpfleury** [comment]
And for the record, here are other links (not about filter explanations) that are broken too:

- First link in the description of *Testing / Garagecoder / Xbr2x*

- The 2 links to cimg.cvs.sourceforge.net in the description of *Karo's tests / About*

- Link *Based on article* in *Testing / Naggobot / Exposure fusion weight map*

**Comment by dtschump** [comment]
Thanks for reporting.
It should be fixed now.

**Comment by jpfleury** [comment]
Yes. Thanks.
