### ISSUE TITLE
Gateway Anti-Virus Alert, is GMIC trojan?

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [dtschump/gmic-community#121]
I am tying to download gmic for windows but I got this erro:

> Gateway Anti-Virus Alert
> --
> This request is blocked by the Firewall Gateway Anti-Virus Service. Name: (Cloud Id: 4888292) MalUAgent.MIP (Trojan) blocked.

any help?

**Comment by patdavid** [comment]
No, G'MIC is not a trojan (assuming you got it from a reputable place).

Antivirus programs will sometimes flag legitimate software as malware (false positive).

**Comment by techtonik** [comment]
You can check the file at https://virusscan.jotti.org/
