### ISSUE TITLE
Different files returned depending on download method

### ISSUE THREAD

**Issue by MechaLynx** [dtschump/gmic-community#124]
Scanning `http://gmic.eu/files/prerelease_windows/gmic_gimp2.10_qt_win64.exe` as a URL (and scanning the downloaded file) returns this SHA-256 hash: 

`2b2d4ad7f3224cfa85994f9a1e094def882dc2f5709769c1ce7cf2e017cdc7d5`

but uploading the file and checking it locally returns a different hash: `0f0b5a4dbe679a70bdceaef91e66c73f85ebf5283f6355e3f7df391295980b88`

[Scanning the file through the URL](https://www.virustotal.com/#/file/2b2d4ad7f3224cfa85994f9a1e094def882dc2f5709769c1ce7cf2e017cdc7d5/detection)

[Scanning the uploaded file](https://www.virustotal.com/#/file/0f0b5a4dbe679a70bdceaef91e66c73f85ebf5283f6355e3f7df391295980b88/detection)

The file sizes are identical so this is very strange. Neither one gets any hits from the engines but it will likely raise some red flags with people. In either case, the server should return the same file, not sure why the discrepancy would exist.

**Comment by dtschump** [comment]
Don't know what happened. This is a quite old issue, not sure it still holds.
