### ISSUE TITLE
Windows "How to create a custom filter in the G’mic plug in"

### ISSUE THREAD

**Issue by jabowery** [dtschump/gmic-community#131]
Quoting [How to create a custom filter in the G’mic plug in](https://github.com/dtschump/gmic-community/wiki/How-to-create-a-custom-filter-in-the-G%E2%80%99mic-plug-in):

> All the user-defined filters that you make have to be written in one single text file called “.gmic” under linux or MacOS and only “gmic” under Windows (there’s a dot at the start of the filename under linux or MacOS, not under Windows). You need to create that file in your home directory if you are under linux or MacOS and in your Application Data folder if your are under Windows.

If one enters `%appdata%` under Windows 7, it takes one to `myusername\AppData\Roaming` where one finds a *folder* named `gmic`, within which one finds files such as `update236.gmic`.

If one attempts to create a *file* named `%appdata%\gmic` one will be editing the *folder*.

**Comment by IainMF** [comment]
Create a file called user.gmic in `myusername\AppData\Roaming`
