### ISSUE TITLE
Command line error with arguments containing spaces

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic-community#14]
**Config:** G'MIC and G'MIC for GIMP 1.6.5.1 on Xubuntu 15.04

When text contains spaces, the filter *Rendering / Quick copyright* works inside GIMP, but fails in the command line.

With default settings, the following is output in the log:

    [gmic_gimp]./preview/ -v -99 -gimp_quick_copyright "\251 G'MIC",27,255,255,255,128,1,3,5,1

This command:

    gmic source.png -gimp_quick_copyright "\251 G'MIC",27,255,255,255,128,1,3,5,1 -o source2.png

fails:

    *** Error *** Command '-gimp_quick_copyright': Undefined argument '$2', in expression '$2' (for 1 argument specified).

If we remove the space, it works:

    gmic source.png -gimp_quick_copyright "\251_G'MIC",27,255,255,255,128,1,3,5,1 -o source2.png

**Comment by jpfleury** [comment]
Same error with the filter *Degradations / Visible watermark*.

**Comment by dtschump** [comment]
If you use the command line, you must take care of the possible substitutions and special characters done by the shell (bash probably in your case).
So, in this case, you need to escape the double quotes:

    gmic source.png -gimp_quick_copyright \"\\251_G'MIC\",27,255,255,255,128,1,3,5,1 -o source2.png

**Comment by jpfleury** [comment]
It doesn't work either, it opens a kind of shell prompt. Note that the copyright symbol `\251` doesn't have to be escaped. If you test the command:

    gmic source.png -gimp_quick_copyright "\251_G'MIC",27,255,255,255,128,1,3,5,1 -o source2.png

The symbol appears correctly in the resulting image.

**Comment by jpfleury** [comment]
Note that this problem occurs with all arguments containing spaces. Examples with default settings:

- *Arrays & tiles / Ascii art*

        gmic source.png -gimp_asciiart 5," .oO0",16,15,16,2,0,0.2,0,0,"/tmp/gmic","gmic_asciiart.txt" -o source2.png

- *Colors / User-defined*

        gmic source.png -gimp_custom_transform "i","i + 90*(x/w)*cos(i/10)","i","i","i","i",0 -o source2.png

- *Deformations / Cartesian transform*

        gmic source.png -gimp_custom_deformation "(w+h)/20 * cos(y*20/h)","(w+h)/20 * sin(x*20/w)",1,1,1 -o source2.png

- *Deformations / Polar transform*

        gmic source.png -gimp_transform_polar 0,50,50,"r + R/10*cos(a*5)","a",1 -o source2.png

Another way to reproduce the bug is to put spaces in a path, for example `/tmp/output folder`:

    gmic source.png -gimp_animate_elevation3d 10,1,0,"/tmp/output folder",100,1,1024,1024,2,0.8,35,0,0,45,0,0,-100,0.5,0.7,0.8,35,0,360,45,0,0,-100,0.5,0.7 -o source2.png

**Comment by dtschump** [comment]
My fault, I should have escaped the single quote too. This works (with bash):

    gmic source.png -gimp_quick_copyright \"\\251 G\'MIC\",27,255,255,255,128,1,3,5,1

On Windows of course, this will be a different kind of escaping probably. Usually, it is not "trivial" to convert a G'MIC command line into something you can invoke from the bash, especially when the command line has spaces, quotes, double quotes, parentheses, brackets, and so on..
All those characters have also a particular meaning in bash, and you need to escape them most of the time, to be sure G'MIC really get the full command line, with all the desired characters in it.

**Comment by dtschump** [comment]
(and of course, all this is perfectly normal and expected :) ).

**Comment by jpfleury** [comment]
Indeed. Thanks a lot, and sorry for the noise.
