### ISSUE TITLE
C Lib No Docs

### ISSUE THREAD

**Issue by juancarlospaco** [dtschump/gmic-community#140]
C Lib needs Documentation, return and argument types and descriptions, examples if possible.
 
I want to create a [Nim GMIC library](https://nim-lang.org/docs/manual.html#foreign-function-interface) but cant find any Docs.

[This Tweet motivated the bug.](https://twitter.com/gmic_ip/status/1085547786928640000)
:cat:

**Comment by dtschump** [comment]
@tobybear , any doc available somewhere ?

**Comment by tobybear** [comment]
The file use_libcgmic.c contains a simple usage example with description of most of the interface parameters, but I will try to compile with the latest GMIC version and see if I can come up with a better documentation.

**Comment by juancarlospaco** [comment]
The most important are the **Types** of returns and arguments of functions.

**Comment by juancarlospaco** [comment]
Any news :grey_question:
