### ISSUE TITLE
gmic-gimp 1.7.9 crashing GIMP 2.10.6 (Ubuntu 18.10)

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dtschump/gmic-community#143]
I just install *gmic-gimp* on Ubuntu 18.10, hoping to experiment with GMIC.

However, already simple clicks in the GMIC window crash the plugin, e.g., selecting "UPDATE INFORMATION" at the bottom. For a fraction of a second, information in the filter area appears, just to be followed by the dreaded:

> GIMP Message
>
> Plug-in crashed: "gmic_gimp"
> (/usr/lib/gimp/2.0/plug-ins/gmic_gimp)
>
> The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side.

dialog.

`gimp --verbose` says `/usr/lib/gimp/2.0/plug-ins/gmic_gimp: fatal error: Segmentation fault`

The next time, just selecting the `Filters`→`G'MIC…` menu entry already crashes after showing the previous window for a split second.

**Comment by dtschump** [comment]
I think Canonical doesn't really care about the gmic package. This package is basically managed by the Debian maintainer instead and is automatically imported into Ubuntu from Debian when a new Debian version is released.
Fortunately, the Debian maintainer of the gmic package has recently upgraded it to 2.4.4, so it may be up to date in a near future :)
