### ISSUE TITLE
Cannot install GMIC 2.4.5 over 1.7.9 on Ubuntu 18.10

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dtschump/gmic-community#144]
I cannot install your `.deb` from Ubuntu 18.04, which https://gmic.eu/download.shtml claims to be compatible with 18.10:

`dpkg -i gmic_ubuntu_bionic_amd64.deb` results in:
> Unpacking gmic (2.4.5) over (1.7.9+zart-4.1build1) ...
> dpkg: error processing archive /home/marcel/Downloads/gmic_ubuntu_bionic_amd64.deb (--install):
 trying to overwrite '/usr/lib/gimp/2.0/plug-ins/gmic_film_cluts.gmz', which is also in package gimp-gmic 1.7.9+zart-4.1build1
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)

**Comment by MarcelWaldvogel** [comment]
Installing it after removing the 1.7.9 GMIC first gives the following error:

> dpkg: dependency problems prevent configuration of gmic:
>  gmic depends on libilmbase12 (>= 1.0.1); however:
>  Package libilmbase12 is not installed.
> gmic depends on libopenexr22; however:
>  Package libopenexr22 is not installed.

Both packages are not part of *cosmic*.

**Comment by MarcelWaldvogel** [comment]
Here, they are called (excerpts from `apt search openexr` and `apt search ilmbase`):

```
libopenexr23/cosmic,now 2.2.1-4build1 amd64 [installed,automatic]
  runtime files for the OpenEXR image library

libilmbase23/cosmic,now 2.2.1-2ubuntu1 amd64 [installed,automatic]
  several utility libraries from ILM used by OpenEXR
```

Could you have `libilmbase12` and `libopenexr22` hanging around from *bionic*?

So maybe you want to change the dependencies to `libilmbase12 | libilmbase23` and `libopenexr22 | libopenexr23`?

**Comment by MarcelWaldvogel** [comment]
Just changing the dependencies is not enough, as the `gmic` binary (and maybe other parts) references `libIlmImf-2_2.so.22` and `libHalf.so.12` by name (`ldd` output). To use the `Depends:`-modified `gmic_ubuntu_bionic_amd64.deb`, I therefore also needed to symlink them to `*.23`.

So maybe a real release for 18.10/cosmic would be best.

**Comment by MarcelWaldvogel** [comment]
The plugin works (just one file to put into `~/.config/GIMP/2.10/plug-ins`) and [the GMIC code itself compiles fine](https://framagit.org/dtschump/gmic/issues/2) (`make install` does not work without also compiling the plugin locally, where I did not bother to determine all the dependencies).

**Comment by dtschump** [comment]
Today, I've done a fresh install of Ubuntu 18.10 in a VM, and was able to generate a .deb package for installing G'MIC and its plugins for GIMP and Krita.
The link is here : https://gmic.eu/files/prerelease_linux/gmic_ubuntu_cosmic_amd64.deb

It would be nice if you could test and report any issues with this .deb package.

**Comment by MarcelWaldvogel** [comment]
A quick test did not show any problems in either GIMP or Krita (hopefully I had completetely uninstalled my own hacks.) Thanks a bunch!
