### ISSUE TITLE
please provide a package with the clut files

### ISSUE THREAD

**Issue by calestyo** [dtschump/gmic-community#15]
Hey.

Could you please provide a package with all the clut files (and specifying their license) so that distros could more easily package these for offline use?

Thanks,
Chris.

**Comment by dtschump** [comment]
I've put a .zip file with all the external data files loaded by G'MIC filters here:

http://gmic.eu/gmic_all_data.zip

The license used is : cc-by-sa : http://creativecommons.org/licenses/by-sa/4.0/

**Comment by calestyo** [comment]
Thx :)

**Comment by keithito** [comment]
Hi! Sorry to bother you, but the link to http://gmic.eu/gmic_all_data.zip appears to be broken. Is there an alternate place to download them? Thanks!

**Comment by rlafuente** [comment]
is a package stil available somewhere? The link http://gmic.eu/gmic_all_data.zip is 404 :/

**Comment by dtschump** [comment]
Should be fixed now.
However, this file does not contain the CLUTs in .cube format. CLUTs in G'MIC are stored with a specific compression algorithm that only G'MIC is able to decompress for the moment.

**Comment by rlafuente** [comment]
super, thank you!
