### ISSUE TITLE
A bug when using folder()

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic-community#169]
After testing my own picture mosaic, it appears that the end image actually shrinks when using folder input option. I don't know why, but the fact that it works fine without using folder input suggests that there's a bug within g'mic, and it's not one that I can explain.

**Comment by dtschump** [comment]
This is not clear. We didn't notice any issue with `folder()` so far.
Please provide a **minimal** example where you encounter issues.

**Comment by Reptorian1125** [comment]
note: rep_mosaic_gen has been updated.
1. Open latest Krita 4.2. 
2. Insert input_glob "D:\filetest" rep_mosaic_gen 14,,.76,2 into code[local] using latest g'mic-qt plugin and the code within my pull request.
You get something that looks like - https://i.imgur.com/VboKMfK.jpg
The expected result would be that it fits the whole image and not something like above. I checked with autocrop and no input_glob, and it's not within the rep_mosaic_gen code.

**Comment by Reptorian1125** [comment]
I found the solution to the bug though I had to add commands just to make it work and ideally, that shouldn't be needed to get the code to work. Here it is for your reference. 

input_glob "D:\filetest" to_a rep_aspect_crop_2d {w#0},{h#0} r {w#0},{h#0},1,4,5 rep_mosaic_gen 14,,.76,2

Now, I think I'll update the mosaic filter with this in mind.
