### ISSUE TITLE
film emulation presets point to non-existent uri's

### ISSUE THREAD

**Issue by ghost** [dtschump/gmic-community#17]
All the film emulation presets point to uri's (sourceforge) which do not exist. Even the link given in "download presets" is broken, giving no way to download the presets at all.

**Comment by dtschump** [comment]
Which version of G'MIC do you use ? All links have been updated when we have moved to http://gmic.eu.You are probably using a quite old version ? Just curious :)

**Comment by tkelley65** [comment]
Ah, Debian Jessie, they must not have updated the source since they
packaged it. I filed a bug. Thanks!

Tim Kelley
