### ISSUE TITLE
G'MIC 1.6.5.2 64bit (Win7) [smooth] anisotropic preview error

### ISSUE THREAD

**Issue by Espermachine** [dtschump/gmic-community#18]
![error anisotropic smoothing](https://cloud.githubusercontent.com/assets/14295623/9879520/03d8f776-5bc8-11e5-82a4-3d2ad4b63711.png)

**Comment by dtschump** [comment]
Thanks. Should be fixed after a filter update.
Let me know :)

**Comment by Espermachine** [comment]
Its working now. Thanks for the lightning quick fix !
