### ISSUE TITLE
Error with Graphix Colors

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic-community#19]
Go to *Artistic / Graphic boost* and for *Merging option*, choose *Graphix Colors*. We have this error:

    [gmic_gimp]./error/ *** Error in ./gimp_graphic_boost4/*repeat/*local/*local/*if/gimp_compose_graphixcolor/ *** Unknown filename '@gimp'.

Version: G'MIC pour GIMP 1.6.5.2 - Linux 64 bits

**Comment by jpfleury** [comment]
Idem for *Artistic / Graphic novel*: for option *Mixer*, choose *Graphix Colors*:

    [gmic_gimp]./error/ *** Error in ./gimp_graphic_novelfxl/*repeat/*local/*local/*if/gimp_compose_graphixcolor/ *** Unknown filename '@gimp'.

**Comment by dtschump** [comment]
Fixed, thanks.
