### ISSUE TITLE
Gmic + Node editor

### ISSUE THREAD

**Issue by leiserfg** [dtschump/gmic-community#199]
I think that with the amount of functions/fiters of gmic plus a node editor (like https://github.com/paceholder/nodeeditor) as a more user-friendly way of composition, is possible to make from a non destructive image editor to a software able tor replace substance designer.

**Comment by afr-e** [comment]
I don't think there is any interest in developing a node editor for G'MIC, though I would love to see someone make and maintain one. 😉 I would try it in a heartbeat.

**Comment by h3lge** [comment]
You can simply use gmic nodes in Natron to achieve that (https://natron.readthedocs.io/en/rb-2.3/_groupGMIC.html).

**Comment by afr-e** [comment]
@leiserfg You might be interested in this development. https://discuss.pixls.us/t/node-based-image-editing/21400
