### ISSUE TITLE
remembering marker points in the colorize (interactive) filter when quitting GIMP/Krita

### ISSUE THREAD

**Issue by narayaan** [dtschump/gmic-community#2]
At the moment there's no possibility to keep your marker points in the colorize (interactive) filter after quiting GIMP (or Krita). For example if I want to start to colorize lineart with the colorize (interactive) filter today and continue working on it tomorrow I have no choice but keeping my pc and GIMP running.

It would be really nice if there would be a way to preserve these markers which would make it easier to keep progressing with one image stretched over several days.. I'm not exactly sure if this something that can be coded in G'mic but this would be a helpfull improvement to the filter.

**Comment by dtschump** [comment]
It should work if you add your filter to the Faves after you ran it one time. Setting it as a Fave should save the marker positions.

**Comment by narayaan** [comment]
Hi, I saved the filter to my faves but to no avail, maybe I'm doing something wrong.
Anyway, here are some steps to reproduce. I use the G'mic plugin in  GIMP on Windows.



1) I open GIMP
2) I open an image
3) I use the colorize (interactive) filer and put some marker points on my image, i press spacebar to create my result and press enter 
4) I close the file and GIMP
5) I restart GIMP and open the same image
6) I open the filter colorize (interactive)
7) marker points are not preserved

**Comment by narayaan** [comment]
Hi David. I retested this today, but this issue persists...
