### ISSUE TITLE
Error with Artistic / Photoillustration

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic-community#20]
Go to *Artistic / Photoillustration*. For *Smoothing style*, choose *selective gaussian*:

    [gmic_gimp]./error/ *** Error in ./gimp_tk_photoillustration_preview/gimp_split_preview/*repeat/(...)/gimp_tk_photoillustration/*repeat/*local/*if/ *** Command '-gimp_selective_smoothing': Undefined argument '$7', in expression '$7' (for 6 arguments specified).

and choose *wavelet*:

    [gmic_gimp]./error/ *** Error in ./gimp_tk_photoillustration_preview/gimp_split_preview/*repeat/(...)/gimp_tk_photoillustration/*repeat/*local/*if/ *** Command '-gimp_haar_smoothing': Undefined argument '$6', in expression '$6' (for 5 arguments specified).

Other smoothing styles work.

Version: G'MIC pour GIMP 1.6.5.2 - Linux 64 bits

**Comment by dtschump** [comment]
Fixed, thanks!
