### ISSUE TITLE
Returning filter parameter values - problem with certain symbols

### ISSUE THREAD

**Issue by garagecoder** [dtschump/gmic-community#21]
Windows gimp plugin, version 1.6.6.1 (gimp 2.8.10)

There seems to be a problem returning text values containing the less than symbol "<", presumably due to markup expecting closed tags.  For example:
```
#@gimp Test: test_return,test_return(1)
#@gimp : Code = text(1,"\n\n\n\n")
test_return : -skip ${1=,}
  -u "{watch<this}"
```
Instead of the expected text it returns the parameter name.  Perhaps there is a workaround?

**Comment by dtschump** [comment]
Hello Andy!
Back in the business ? :)

This should work, for 1.6.6.1:

    #@gimp Test: test_return,test_return(1)
    #@gimp : Code = text(1,"\n\n\n\n")
    test_return : -skip ${1=,}
      -u "{watch&lt;this}"

Beware, it won't work for previous versions, so maybe you should check the version:

    -if {$_version<1661} -u {watch<this} -else -u {watch&lt;this} -endif

Allowing the pango markdown syntax in the text field is a convenient way also to put strings in different languages (japanese for instance). This was hardly possible before.

**Comment by garagecoder** [comment]
Just trying to keep up to date when I can :)
That should be OK, the string is user supplied but it can be search/replaced so no problem hopefully.

**Comment by dtschump** [comment]
I'm pleased to see you are not definitely gone by the way :)
I find the new features in 1.6.6.1 are really cool. I wish we would have those when we have looked at the 'Seamcarve' implementation in G'MIC. It could have been really easier to do.

**Comment by garagecoder** [comment]
It's always nice to be missed (even a little), thanks!
Yes the new features always get me thinking about alternative ways of doing things, or ideas which just weren't possible before.  I do at least try to follow the updates because there's often something surprising.
I had a small hope using gegl buffers would fix the silly opacity zero problem (where it doesn't bother to copy other channels) but alas... we're still at the mercy of gimp :)
