### ISSUE TITLE
when you install gmic on windows gimp 2.8.14, gimp is not able to read pdf anymore 

### ISSUE THREAD

**Issue by gpciceri** [dtschump/gmic-community#22]
it seems there's a conflict of libraries. if you do a fresh install of gimp for windows and then install gmic, you are not able to read pdf files anymore.

tested on gimp 2.8.14 windows 32 bit, portable edition.

**Comment by dtschump** [comment]
This sounds like a .dll compatibility issue.
The new installer should fix this : https://discuss.pixls.us/t/using-the-windows-installer-for-version-2-0-3-of-gmic/4825
