### ISSUE TITLE
Empty $HOME/.gmic file leads to SIGSEGV (Segmentation Fault) on gmic_gimp plug-in load.

### ISSUE THREAD

**Issue by grosgood** [dtschump/gmic-community#23]
Hello David,
One of those silly corner cases that borders on user error. Seems I can crash the gmic_gimp plug-in by creating an empty (0 byte content) .gmic file, an exercise verging on pointlessness, but I'm prone to such when I'm sleepy or distracted. This has been going on since March on a machine I don't run gmic on all that much, or run Gimp with the plug-in, and when I did, and it crashed, I couldn't be arsed to figure out why, and I'd use some other machine where gmic and gimp gave no trouble. Except today my curiosity got the better of me. While I'm reporting on the current version, I could reproduce this on 1.6.5.2, the oldest gmic I still have running. Probably some sort of notice in the preview window would be nicer than a segfault. 
Particulars:
    Version:
    1.6.8 prerelease #10242015
    
    To reproduce:
    Create an empty .gmic file in $HOME by any suitable means, such as:
    $ touch .gmic
    
    Result: SEGFAULT on plug-in load
    Reproducable: Always
    
    Workaround:
    Delete the empty .gmic file or put something useful in it.
    
    git:
    
    commit f152ba3c5e4b91d38afb5ea0dcb5c63c7ca783ff
    Author: dtschump <David.Tschumperle@gmail.com>
    Date:   Sat Oct 24 14:11:21 2015 +0200
    
        Add Download icon in menu bar of web pages
    
    Failure point: at gmic_gimp.cpp
    1302          } else {
    1303            com.load_raw(filename);
    1304   ------>  if (cimg_sscanf(com,"1 unsigned_cha%c",&sep)==1 && sep=='r')
    1305              CImgList<char>::get_unserialize(com)[0].move_to(_gmic_additional_commands);
    1306            else com.move_to(_gmic_additional_commands);
    1307            add_code_separator = true;
    1308          }
    (gdb) print com
    $1 = {_width = 0, _height = 0, _depth = 0, _spectrum = 0, _is_shared = false, _data = 0x0}
    (gdb) print filename
    $25 = {_width = 1024, _height = 1, _depth = 1, _spectrum = 1,
      _is_shared = false, _data = 0x619000478b80 "/home/gosgood/.gmic"}
    
    Comment: "/home/gosgood/.gmic" exists but is empty,
    gosgood@estella ~ $ ls -l .gmic
    -rw-r--r-- 1 gosgood gosgood 0 Mar  9  2015 .gmic
    
    Backtrace:
    Program received signal SIGSEGV, Segmentation fault.
    rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
    37              movdqu  (%rdi), %xmm0
    (gdb) bt
    #0  rawmemchr () at ../sysdeps/x86_64/rawmemchr.S:37
    #1  0x00007f706ed00358 in _IO_str_init_static_internal (sf=sf@entry=0x7fff8b9ff240, 
        ptr=ptr@entry=0x0, size=size@entry=0, pstart=pstart@entry=0x0) at strops.c:44
    #2  0x00007f706ecf59e7 in _IO_vsscanf (string=0x0, format=0xd657a0 "1 unsigned_cha%c", 
        args=0x7fff8b9ff3c0) at iovsscanf.c:43
    #3  0x00007f7074267b3b in vsscanf () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libasan.so.1
    #4  0x00007f7074267c49 in sscanf () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libasan.so.1
    #5  0x00000000004148ef in update_filters (try_net_update=false, is_silent=true)
        at gmic_gimp.cpp:1304
    #6  0x000000000042e9b3 in gmic_run (name=0x60200000d270 "plug-in-gmic", nparams=3, 
        param=0x60c00000b5c0, nreturn_vals=0x7fff8ba00414, return_vals=0x7fff8ba00418)
        at gmic_gimp.cpp:4247
    #7  0x00007f707388a1f5 in gimp_proc_run (proc_run=0x6190000016c0) at gimp.c:2019
    #8  0x00007f7073889e8d in gimp_loop () at gimp.c:1853
    #9  0x00007f7073887d32 in gimp_main (info=0x113d060 <PLUG_IN_INFO>, argc=6, argv=0x7fff8ba00668)
        at gimp.c:516
    #10 0x000000000042f4d5 in main (argc=6, argv=0x7fff8ba00668) at gmic_gimp.cpp:4388

**Comment by dtschump** [comment]
Thanks Garry, this is fixed in : https://github.com/dtschump/gmic-minimal/commit/a1c36be542bd4a5d89c6fa14b111d6c671d7eef2

**Comment by grosgood** [comment]
Hello David,
Synced and retested. Works everywhere where once it didn't. Closing now. Thank you for the overnight delivery.
