### ISSUE TITLE
Zart Status?

### ISSUE THREAD

**Issue by sperglord8008s** [dtschump/gmic-community#247]
Can anybody update me on the status of Zart? I really think its under advertised. Should be pushed into the light I really think if you integrated Zart with VLC or VirtualDub with the ability to use rtsp streams you would have a 10 fold increase in users and probably a bunch more financial contributions to boot!

Also If anybody has a pointer towards the latest Windows binary or instructions for Zart that would be super awesome. 

Thanks again for the amazing gmic you guys rock.

**Comment by afr-e** [comment]
Repository: https://github.com/c-koi/zart
Instructions: https://gmic.eu/download.html
