### ISSUE TITLE
Size of the GMIC window

### ISSUE THREAD

**Issue by shreedhar2015** [dtschump/gmic-community#25]
The smallest size of the GMIC pop-up window on my laptop is too big for me to see the APPLY button at the bottom. How do I resize it?
![screenshot 1](https://cloud.githubusercontent.com/assets/15703860/11015401/6f9803be-8583-11e5-8964-c7537fc0ef24.png)

**Comment by dtschump** [comment]
Maybe selecting 'Preview size' -> *Small* or *Tiny* solves the problem ?

**Comment by shreedhar2015** [comment]
Fantastic! It does work. 
So depending on the preview size, the minimum size of GMIC window changes. 
Seems reasonable. Thanks a ton for such an immediate response.

**Comment by dtschump** [comment]
Yes, but one thing still worries me. The default preview size should be computed such that you can see the entire plug-in windows on the screen when running it.
May I ask what screen resolution do you use, as well as your input image size too ?

**Comment by shreedhar2015** [comment]
Surely.

I have a Sony Vaio Flip 13 Tablet Computer with 13 inch screen and 1920 by
1080 (the recommended ) resolution. The OS is Win 10.

In GIMP I opened a JPG file of size 2783 by 4276 pixels with 300 ppi
resolution.

Does this answer your question?

Shreedhar

**Comment by dtschump** [comment]
I need to analyse why those particular numbers end up with a too-bug windows on the screen.
Not sure I'll find why :)

**Comment by shreedhar2015** [comment]
Thanks for your consideration.

Here is one more piece of information:

Each time I start GIMP afresh and use GMIC, I have to change the preview
size. But if I close GMIC only and then in the same session of GIMP open
GMIC again, it opens with previous defaults.

May be you can make it remember the last default? That way, user have to
change the preview window only the first time.

It is not a perfect solution but still better than what it is now !

Shreedhar
