### ISSUE TITLE
Not able to load Png image

### ISSUE THREAD

**Issue by marcel-bariou** [dtschump/gmic-community#250]
Hello, I acquired your book, excellent job thank you! Now I use your CImg library and as soon as I have 3 euros and six cents I will support you with some cash. So I am trying to use your famous library to process PNG image build with libpng12 and  and the C++ wrapper libpng++. This image is the ortho-projection of a tomographic slice of a cloud points to process lidar data as image for objects detection. To improve object detection in the image (pseudo circle) I need to do an morphological erosion on the image, before processing ahead. It works with *.bmp format but not with *.png format. Hereinafter the fragment of code :

``
CImg<unsigned char> img("/home/mbariou/PointCloud/Repository/dmtForest/pngGraph/slice-TerTrees.bmp");
CImg<unsigned char>  B=CImg<unsigned char> (3.3).fill(1);
CImg<unsigned char> imgErode = img.get_erode(B);
    imgErode.display("Eroded Image");
  return 0;
``

I need to use *.png for memory space issue 197591718 (bmp) versus  337519 (png), and all my process is done with *.png images. 
When I do a checking of the *.png file,  with ImageMagick,it seems correct 
identify slice-TerTrees.png
slice-TerTrees.png PNG 14283x13833 14283x13833+0+0 8-bit Gray 256c 333482B 0.000u 0:00.000

More on Gimp 2.10.18 I load the *png image correctly and your plugin process finely for the morphological erosion with the previous *.png image. Here the exception message : 
`
convert-im6.q16: no images defined `pnm:-' @ error/convert.c/ConvertImageCommand/3258.
convert-im6.q16: no images defined `pnm:-' @ error/convert.c/ConvertImageCommand/3258.
convert-im6.q16: no images defined `pnm:-' @ error/convert.c/ConvertImageCommand/3258.

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/home/mbariou/PointCloud/Repository/dmtForest/pngGraph/slice-TerTrees.png'.
terminate called after throwing an instance of 'cimg_library::CImgIOException'
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/home/mbariou/PointCloud/Repository/dmtForest/pngGraph/slice-TerTrees.png'.
Aborted (core dumped)
`
Some hints, some help where Am I wrong ? 
Thank for your follow up.

Marcel Bariou

**Comment by dtschump** [comment]
Hello,
I'd say that if you use CImg with .png, you should really try activate the `-Dcimg_use_png` macro, then link your executable with `-lpng -lz`. It enables the native support of .png files in CImg, and it works pretty well.

Otherwise, saving/loading .png will be done by an external call to 'convert' from ImageMagick, and this is not optimal (still, it should work anyway, so that's a bit strange).

**Comment by marcel-bariou** [comment]
Thanks for your answer
I try :
'
g++ -Wall -fexceptions -O2 -std=gnu++17 -g -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/liblas/include -I/usr/include/png++ -I/usr/include/boost -I/usr/include/boost/filesystem -I/usr/local/imgmagick/include/ImageMagick-7 -I/usr/include/python3.8 -c /home/mbariou/WKSCOMPILE/RECONSTRUCTION_CPP/projCimg/projCimg/main.cpp -o obj/Release/main.o
g++ -L/usr/include/boost -o bin/Release/projCimg obj/Release/main.o  -s -Dcimg_use_png -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16  /usr/local/liblas/lib/liblas.so /usr/lib/x86_64-linux-gnu/libpng12.so.0 /usr/lib/x86_64-linux-gnu/libpng12.a /lib/x86_64-linux-gnu/libz.so.1.2.11 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /usr/local/imgmagick/lib/libMagick++-7.Q16HDRI.so /usr/lib/x86_64-linux-gnu/libpng16.so.16 /usr/lib/x86_64-linux-gnu/libproj.so /usr/lib/llvm-10/lib/libomp.so.5 /usr/lib/x86_64-linux-gnu/libpython3.8.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libz.so
Output file is bin/Release/projCimg with size 1.03 MB
'
But same exception message at execution Thanks

**Comment by dtschump** [comment]
I'd say:
~~~
g++ -Wall -fexceptions -O2 -std=gnu++17 -g -Dcimg_use_png ...
~~~
You really need to put the `-Dcimg_use_png` flag somewhere to be sure to 'unlock' the libpng related functions in CImg.

**Comment by marcel-bariou** [comment]
I was in a hurry before to left for other task, I made a mismatch it's OK, thanks for your help. Later maybe, for other functionalities of you library! Sorry for the disturb
