### ISSUE TITLE
Strange Output

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic-community#251]
Test this code, and you'll realize something is wrong.

```
rep_test_code:
skip ${1=50%}
position={($1+1)}
echo $position
```
```
C:\Users\User\Downloads>gmic rep_test_code
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./rep_test_code/ 0
[gmic]-0./ End G'MIC interpreter.
```

The evidence of the bug is the output of echo is incorrect. Using sum() gives correct output.

**Comment by Reptorian1125** [comment]
Afre explained to me that I need to be more careful with percentages. Percentage in case of ($1+1) has no meaning while in (1+$1), it does.

**Comment by dtschump** [comment]
That's because % has two meanings :
- a%b means 'a modulo b'.
- a% means 'a divided by 100'.

So, 10%+1 means '10 modulo 1',  not '0.1+1'.
Add parentheses to disambiguate the cases: (10%)+1
