### ISSUE TITLE
Problem on case insensitive filesystems

### ISSUE THREAD

**Issue by prusnak** [dtschump/gmic-community#255]
Folder `tutorial` contains both `images` and `Images` sub-folders.

This fails when checking out the repository on case insensitive filesystems.

**Comment by jtojnar** [comment]
Opened a fix in https://github.com/dtschump/gmic-community/pull/256

**Comment by uri-canva** [comment]
I think they're semantically different though: `Images` represents the `Images` tutorial, where `images` represents image files. That's why there's a `tutorial/Images/images` directory.

**Comment by Reptorian1125** [comment]
This is fixed.
