### ISSUE TITLE
gmic compile warning Version 1.6.8 (pre-release #111015)

### ISSUE THREAD

**Issue by orti1980** [dtschump/gmic-community#27]
OpenEXR version 2.2.0.4

make debug
make "CFLAGS+=-Dgmic_build -Dcimg_use_zlib -I/usr/include -Dgmic_prerelease="\\\"`date +%m%d%y`\\\"" -std=c++11 -Wall -W -Dcimg_use_vt100 -Dcimg_use_abort -Dcimg_use_png -Dcimg_use_jpeg -Dcimg_use_tiff -Dcimg_use_curl -Dcimg_use_fftw3 -Dgmic_is_parallel -fopenmp -Dcimg_use_openmp -Dcimg_display=1 -Dcimg_appname=\\\"gmic\\\" -I/usr/X11R6/include  -Dcimg_use_openexr -I/usr/include/OpenEXR -Dcimg_use_opencv  `pkg-config opencv --cflags` -I/usr/include/opencv  -ansi -pedantic -Dcimg_verbosity=3 -g -fsanitize=address " "LIBS+=-lz -L/usr/lib -lm -lpng -lz -ljpeg -ltiff -lcurl -lfftw3 -lfftw3_threads -lpthread -lgomp -L/usr/X11R6/lib -lX11 -lpthread  -lIlmImf -lHalf `pkg-config opencv --libs` -lopencv_core -lopencv_highgui " gmic
make[1]: Entering directory '/home/orti/Downloads/gmic-master/src'
g++ -o gmic gmic.cpp -Dgmic_main -Dgmic_build -Dcimg_use_zlib -I/usr/include -Dgmic_prerelease=\"111015\" -std=c++11 -Wall -W -Dcimg_use_vt100 -Dcimg_use_abort -Dcimg_use_png -Dcimg_use_jpeg -Dcimg_use_tiff -Dcimg_use_curl -Dcimg_use_fftw3 -Dgmic_is_parallel -fopenmp -Dcimg_use_openmp -Dcimg_display=1 -Dcimg_appname=\"gmic\" -I/usr/X11R6/include  -Dcimg_use_openexr -I/usr/include/OpenEXR -Dcimg_use_opencv  -I/usr/include/opencv  -I/usr/include/opencv  -ansi -pedantic -Dcimg_verbosity=3 -g -fsanitize=address  -lz -L/usr/lib -lm -lpng -lz -ljpeg -ltiff -lcurl -lfftw3 -lfftw3_threads -lpthread -lgomp -L/usr/X11R6/lib -lX11 -lpthread  -lIlmImf -lHalf -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab  -lopencv_core -lopencv_highgui 
In file included from /usr/include/OpenEXR/ImfXdr.h:107:0,
                 from /usr/include/OpenEXR/ImfGenericOutputFile.h:40,
                 from /usr/include/OpenEXR/ImfTiledOutputFile.h:50,
                 from /usr/include/OpenEXR/ImfInputFile.h:48,
                 from ./CImg.h:425,
                 from gmic.h:172,
                 from gmic.cpp:2141:
/usr/include/OpenEXR/IexMathExc.h:49:36: Warnung: Beim Ausführen des Arguments 1 des Makros DEFINE_EXC_EXP: Leere Makroargumente sind nach ISO-C++98 unbestimmt [-Wpedantic]
 DEFINE_EXC (OverflowExc,    MathExc) // Overflow
                                    ^
/usr/include/OpenEXR/IexMathExc.h:50:36: Warnung: Beim Ausführen des Arguments 1 des Makros DEFINE_EXC_EXP: Leere Makroargumente sind nach ISO-C++98 unbestimmt [-Wpedantic]
 DEFINE_EXC (UnderflowExc,   MathExc) // Underflow
                                    ^
/usr/include/OpenEXR/IexMathExc.h:51:36: Warnung: Beim Ausführen des Arguments 1 des Makros DEFINE_EXC_EXP: Leere Makroargumente sind nach ISO-C++98 unbestimmt [-Wpedantic]
 DEFINE_EXC (DivzeroExc,     MathExc) // Division by zero
                                    ^
/usr/include/OpenEXR/IexMathExc.h:52:36: Warnung: Beim Ausführen des Arguments 1 des Makros DEFINE_EXC_EXP: Leere Makroargumente sind nach ISO-C++98 unbestimmt [-Wpedantic]
 DEFINE_EXC (InexactExc,     MathExc) // Inexact result
                                    ^
/usr/include/OpenEXR/IexMathExc.h:53:36: Warnung: Beim Ausführen des Arguments 1 des Makros DEFINE_EXC_EXP: Leere Makroargumente sind nach ISO-C++98 unbestimmt [-Wpedantic]
 DEFINE_EXC (InvalidFpOpExc, MathExc) // Invalid operation
                                    ^
In file included from /usr/include/OpenEXR/ImfGenericOutputFile.h:40:0,
                 from /usr/include/OpenEXR/ImfTiledOutputFile.h:50,
                 from /usr/include/OpenEXR/ImfInputFile.h:48,
                 from ./CImg.h:425,
                 from gmic.h:172,
                 from gmic.cpp:2141:
/usr/include/OpenEXR/ImfXdr.h:833:34: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
     u.i = ((Int64) b[0]        & 0x00000000000000ffULL) |
                                  ^
/usr/include/OpenEXR/ImfXdr.h:834:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[1] << 8)  & 0x000000000000ff00ULL) |
                           ^
/usr/include/OpenEXR/ImfXdr.h:835:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[2] << 16) & 0x0000000000ff0000ULL) |
                           ^
/usr/include/OpenEXR/ImfXdr.h:836:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[3] << 24) & 0x00000000ff000000ULL) |
                           ^
/usr/include/OpenEXR/ImfXdr.h:837:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[4] << 32) & 0x000000ff00000000ULL) |
                           ^
/usr/include/OpenEXR/ImfXdr.h:838:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[5] << 40) & 0x0000ff0000000000ULL) |
                           ^
/usr/include/OpenEXR/ImfXdr.h:839:27: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
   (((Int64) b[6] << 48) & 0x00ff000000000000ULL) |
                           ^
In file included from /usr/include/OpenEXR/ImathMatrix.h:47:0,
                 from /usr/include/OpenEXR/ImfMatrixAttribute.h:50,
                 from ./CImg.h:427,
                 from gmic.h:172,
                 from gmic.cpp:2141:
/usr/include/OpenEXR/ImathFun.h:263:19: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
     return (u.i & 0x7ff0000000000000LL) != 0x7ff0000000000000LL;
                   ^
/usr/include/OpenEXR/ImathFun.h:263:44: Warnung: C++11 long long Ganzzahlkonstante verwendet [-Wlong-long]
     return (u.i & 0x7ff0000000000000LL) != 0x7ff0000000000000LL;
                                            ^
In file included from /usr/include/OpenEXR/ImfGenericOutputFile.h:40:0,
                 from /usr/include/OpenEXR/ImfTiledOutputFile.h:50,
                 from /usr/include/OpenEXR/ImfInputFile.h:48,
                 from ./CImg.h:425,
                 from gmic.h:172,
                 from gmic.cpp:2141:
/usr/include/OpenEXR/ImfXdr.h:912:44: Warnung: ISO-C++ 1998 unterstützt nicht »long long« [-Wlong-long]
 template <> inline int size <unsigned long long> ()     {return 8;}
                                            ^

OpenEXR version 2.2.0.4

**Comment by dtschump** [comment]
Not related to G'MIC, should be reported to the OpenEXR team instead I guess.
