### ISSUE TITLE
Online Gmic user

### ISSUE THREAD

**Issue by Smiles234** [dtschump/gmic-community#28]
Could someone advise why the online GMIC is not working.  I keep getting a server issue.  I have used this program online for many months and it won't open today.  Yesterday was fine.  Please help

**Comment by Smiles234** [comment]
https://gmicol.greyc.fr/

**Comment by dtschump** [comment]
Hello, thanks for reporting. This doesn't work here either. This is probably a temporary server issue, I'll ask what happens.

**Comment by dtschump** [comment]
G'MICol is working again. I close the issue
