### ISSUE TITLE
Support for TIFF files over 4GB

### ISSUE THREAD

**Issue by ormajollila** [dtschump/gmic-community#29]
Hi,

Are you planning to support tiff files over 4GB (BigTIFF) some day? I read LibTiff has support http://www.remotesensing.org/libtiff/bigtiffpr.html

Or maybe OpenEXR with compression?

I'm trying to create some huge images and 4GB apparently isn't enough.

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/CImg/commit/b25e92f7c069b5fcfd29dddbf0ede245e89a2143 in the CImg Library activates bigtiff support by default. As G'MIC uses CImg, that means G'MIC is able to write bigtiff files as well. Just tested with this command line : 

    $ gmic 4000,400,800 -rand 0,255 -o pouet.tif

and it generates a 5Gb tiff file (and it crashes with the older version).
I haven't tested more than that, but this seems to be a step in the right direction.

**Comment by dtschump** [comment]
I've posted some pre-release binaries for you to test the support of the bigtiff files : 

http://gmic.eu/files/prerelease/

The versions are 1.6.9_pre.
If you have some time to test, just let me know.

**Comment by ormajollila** [comment]
Hi,

Tried it out finally. Seems to be working!

Thanks!
