### ISSUE TITLE
gmic in Kita fails to get network file when "add grain" filter is used

### ISSUE THREAD

**Issue by RomuloPBenedetti** [dtschump/gmic-community#3]
it fails to obtain this for example:
http://gmic.eu/data_film_presets/grain_orwo_np20.cimgz
I tried to download and the download work but is a bin file that comes on.

**Comment by dtschump** [comment]
Yes, grain presets are binary files, in .cimgz format.
I'm not the maintainer of the Krita plug-in, so I cannot help much for those kind of issues.
Have you tried with the G'MIC plug-in for GIMP, to see if that works for you ?

**Comment by RomuloPBenedetti** [comment]
Yes it is working in gimp, I've found it after some tests and research:
https://bugs.kde.org/show_bug.cgi?id=349460
It probably is a downstream packaging problems they say. Thanks and sorry for the wrong place bug reporting. :(

**Comment by dtschump** [comment]
Seems to be a Krita specific issue, can be fixed only by the Krita team. I close this issue.
