### ISSUE TITLE
Warhol filter preview does not match output when applied

### ISSUE THREAD

**Issue by pinba11** [dtschump/gmic-community#32]
The Warhol filter (Artistic -> Warhol) seems to reapply it's settings when the "Apply" button is clicked.  This causes the output image to not match the preview.

The "Color" option does not seem to be deterministic - that is, selecting the same number for Color does not give the same output image each time.  This may be expected behavior, the issue I am pointing out is the preview not matching the output.

To recreate:
- Select Warhol filter
- Set X-tiles to 1
- Set Y-tiles to 1
- Choose arbitrary Smoothness and Color (higher color numbers are easier to notice the error)
- Note what sorts of colors the preview image is showing
- Click apply

Result:  the output image will not match what the preview image was showing.  In addition, the preview will change (since whatever the Color option is controlling does not seem to be exactly deterministic).

**Comment by dtschump** [comment]
Yes, the filter uses random colors each time it is applied, so the colors in the preview and the final result won't match.
