### ISSUE TITLE
Use left mousebutton (+ALT or +CTRL) to remove control points in colorize interactive

### ISSUE THREAD

**Issue by cnikiel** [dtschump/gmic-community#35]
I use a Surface Pro 4 with Krita and the G'Mic Plugin to colorize some lineart.
The Surface pen has by default no right mouse button.
So removing a control point is done by long pressing the pen, the slightest movement disturbs this.

The question would be, if it is possible to use CTRL or ALT together with the left mousebutton to simulate the right click?
That way even with a pure one button mouse it could be possible to remove a control point.

Thank you.

**Comment by dtschump** [comment]
ALT is not very convenient, because of Linux, ALT+Mouse is also used to move a window on the screen.
I've uploaded an update of the filters with the key 'X' instead (so without a need to push the mouse button).
Is it OK like that ?

**Comment by cnikiel** [comment]
Wow, thank you. That was extraordinarily fast. :-)
Could you do something similar for the color picking as well?
Like 'P' for color Picker? (or any other key of your coosing)
Thanks again, the colorizer safes a huge amount of time for me.

2016-01-11 20:58 GMT+01:00, David Tschumperlé <notifications@github.com>:

**Comment by dtschump** [comment]
Yes, it is possible.
It should be OK after a filter refresh.

**Comment by cnikiel** [comment]
You do know that you are awesome, right?
Thanks a lot. Now I just have to figure out how I can get this integrated
into Krita ;-)

2016-01-12 8:39 GMT+01:00 David Tschumperlé <notifications@github.com>:

**Comment by dtschump** [comment]
Thanks.
I'm afraid it won't be as simple in Krita, as they use an older version of G'MIC with no more filter updates.

**Comment by cnikiel** [comment]
I have got a reply from the Krita team.
They are willing to pull this fix and probably a lot of the good stuff that you have written.
But they would like to wait for an official release of G'Mic to pull.
Preferably for me with this fix included 😉
The have asked for a release date of the next official version of G'Mic.
Do you have any date in mind already?
For your reference here is the Krita bugtracker link.
https://bugs.kde.org/show_bug.cgi?id=357880
Thank you and best regards,
Carsten

**Comment by dtschump** [comment]
I've registered in their bugzilla, and answered there. Thanks for reporting.

**Comment by cnikiel** [comment]
Thanks for taking over the initiative.
Looks like you two can come to an agreement.
And the only thing I had to do was write a bit. Awesome.

**Comment by dtschump** [comment]
You know, I have regular discussions with Boud and the rest of the Krita team. The work they do is awesome!

**Comment by cnikiel** [comment]
As is yours. 😉 The time I save just with the interactive comic color filter is huge.
Thanks again.
