### ISSUE TITLE
Tileable rotation crashes G'mic with 'Maximum size factor' = 0

### ISSUE THREAD

**Issue by ObiWanCeleri** [dtschump/gmic-community#38]
G'mic 1.6.8 64 bits (as a plugin)
Gimp 2.8.16
Windows 7 64 bits, 12gb ram

Source RGB picture 1920x1980x3

Calling the G'mic plugin called "Tileable rotation" and dragging the 'Maximum size factor' to zero crashes G'mic instantaneously.

Other parameters :
[X] Preview
All visibles
New layer(s)
Verbose (layer name)
Preview mode ...
Normal
Angle 45
Maximum size factor 0
Array mode None

Re-opening plugin from there on crashes plugin instantaneously. 

Possible solution : Start 'Maximum size factor' variable at 1 instead of 0

Workaround : Quit Gimp, start Gimp, open G'mic and update plugins to reset parameter values.

**Comment by dtschump** [comment]
Doesn't crash for me on Linux 64bits.
When you say "it crashes", does it display an error message somewhere, or does it crash silently ?
Also just a hint : Gimp menu entry *Filters / Reset all filters* is probably a faster workaround :).
Thanks for your help.

**Comment by ObiWanCeleri** [comment]
Got to reproduce it. Here's a screenshot.
![image](https://cloud.githubusercontent.com/assets/16766744/12430306/fc49f1c4-bebc-11e5-858a-68e062d45d92.png)

I am working on a HD picture : 1920x1080x3 
Works fine when I resize the picture --> 1080x1080x3

With the HD picture I clicked on the 'Maximum size factor' handle and used the mouse wheel to bring it to 0 ... G'mic crashed and gave me this message. If you tell me how to generate a log I can send it to you. Hopefully it isn't my machine LOL ;)

**Comment by dtschump** [comment]
Ah, I see then. '0' for Maximum size means 'no limit', and the angle you've specified (or the dimensions of the image) does not fit the very specific constraint of the tileable rotation filter.
If you look at the math behind (http://www.peteryu.ca/tutorials/gimp/rotate_tileable_patterns), you'll see what I mean. This filter can't work nicely with images having arbitrary dimensions.
Of course, on a crap OS as Windows, trying to allocate the needed memory does not raise an exception that can be caught by G'MIC, but makes the plug-in crashes brutally.

**Comment by ObiWanCeleri** [comment]
Ha! Makes sense :)
Too lazy to migrate to Linux ahahahaha

**Comment by ObiWanCeleri** [comment]
I'm actually doing research in GIMP and then 'translating' the results in G'mic; I have 400+ images to work on so there's no way I'm doing this manually for every picture. I've built a shell with AutoIT3 to automate the rest :)

**Comment by ObiWanCeleri** [comment]
So shall I close the issue then?
BTW thanks so much - G'mic is fantabulous :)
