### ISSUE TITLE
libopencv_core2411.dll missing

### ISSUE THREAD

**Issue by YRTV** [dtschump/gmic-community#42]
http://gmic.eu/files/windows/gmic_win64.zip
![image](https://cloud.githubusercontent.com/assets/18060413/14034276/cf4d6f80-f232-11e5-9945-986984e44879.png)

http://gmic.eu/files/windows/gmic_win32.zip works fine.
![image](https://cloud.githubusercontent.com/assets/18060413/14034355/a1a8ba16-f233-11e5-9987-acfead8d5a0d.png)
 Both contain libopencv_core2410.dll.

**Comment by lubeda** [comment]
In the 64bit zip are two dlls on the wrong old level

**Comment by dtschump** [comment]
Thanks for reporting, I've just posted a new pre-compiled package (that replaces the old one) for Win64, which should work as expected.
Could you try and tell me ?

**Comment by lubeda** [comment]
Hello,
after a short test i can say it works.

Thanx

Ludger


Am 25.03.2016 um 11:41 schrieb David Tschumperlé:
