### ISSUE TITLE
gmic-gimp crash in gimp 2.9

### ISSUE THREAD

**Issue by cloudberri** [dtschump/gmic-community#43]
Hi,

I'm running gimp-2.9 and associated libs.  Recently, gmic fails to start within gimp.  Gmic is the latest build from git.  I think this is the relevant bit of the message:  

GEGL-geglmodule.c-Message: Module '/home/richard/Software/gimp-git/lib/gegl-0.3/dot.so' load error: /home/richard/Software/gimp-git/lib/gegl-0.3/dot.so: undefined symbol: gegl_cl_is_accelerated
/home/richard/Software/gimp-git/lib/gimp/2.0/plug-ins/gmic_gimp: fatal error: Segmentation fault

Is it me or is it it?

**Comment by dtschump** [comment]
I've compiled the plugin too few days ago, and it was working well with gimp-2.9.
I'm on Ubuntu, using the git repo for gimp-2.9 as well.
I don't think I was up to date,  but so far I haven't encountered any crash. 
I'll try again tomorrow and see what happens.  Maybe try to compile the plugin like this:

    $ make OPT_CFLAGS="-g -fsanitize=address" gimp

And try running the plugin again, you should get a more detailed error message. 
Thanks for reporting.

**Comment by cloudberri** [comment]
Thanks for reply.
OK.  Recompiled with the above flags.  Same behaviour, and no more verbose.  Installed pstack.  Got it to spit out:
7868: /home/richard/Software/gimp-git/lib/gimp/2.0/plug-ins/gmic_gimp -gimp 14 13 -run 1
(No symbols found)
0x7f643bada810: ???? (7f643f839000, 7f643f839000, 7f643f839000, 7f643f839000, 7f643f839000, 7f643f839000) + ffff809cbfd24644
crawl: Input/output error
Error tracing through process 7868
0x7f643f839000: ????

**Comment by dtschump** [comment]
Ah ok, sorry I forgot to disable the 'strip' command as well.
So we don't get symbols for the debug.
Could you try this one instead : 

    $ make OPT_CFLAGS="-g -fsanitize=address" NOSTRIP=1 gimp

Thanks again !

**Comment by cloudberri** [comment]
Arg.  Nope.  All I've got now is more messages saying:
dot.so: undefined symbol: gegl_cl_is_accelerated

If it *is* anything to do with gegl, I had to pass --without-libavformat to the gegl build; as my version of libavformat is a little old.

**Comment by dtschump** [comment]
Well, I've no more ideas then :(
Will try tomorrow to rebuild the latest version from git, and see if I can reproduce the bug.
I use only very little of GEGL in the plug-in code, so it may be from that, but definitely not sure.

**Comment by cloudberri** [comment]
..my best guess so far is that opencl isn't running.   :-(

**Comment by cloudberri** [comment]
What version of gcc are you using?

**Comment by dtschump** [comment]
I'm using g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010.
I didn't succeed in building the latest sources of GIMP from the git. It seems there is a problem with one header. Not sure what is going on. I had not much time to go ahead , so no news for now :(

**Comment by cloudberri** [comment]
IT WORKS!  thank-you!  (1.7.2pre#051316).  Out of interest, what was the problem?

**Comment by dtschump** [comment]
No idea :)
I've been working hard these last days on the G'MIC code, so maybe I've fixed one bug that was remaining ? Glad to hear it works anyway :)
