### ISSUE TITLE
[Karo's tests] pink test operator bianca: preview error

### ISSUE THREAD

**Issue by phrokton** [dtschump/gmic-community#48]
Windows 10 home 64bit
g'mic 1.7.1
gimp 2.8.16 (https://chocolatey.org/)

![pinkoperatorbianca_previewerror](https://cloud.githubusercontent.com/assets/19551366/15551534/4d93ad7e-226b-11e6-841a-40358ac0ff9f.png)

**Comment by karo11** [comment]
... you have to have the necessary executables in your PATH, that means programs built either with CImg/examples or with Pink software.
Please read the "About section" of Karo's Tests!

**Comment by phrokton** [comment]
Thank you for your swift reply!

> Please read the "About section" of Karo's Tests!

Something is missing.. gotcha. 

Are there no pre-built windows binaries of use_nlmeans.exe ?

since 404:  https://pinkhq.com/download/packages/pink

**Comment by karo11** [comment]
Unluckily not, neither for CImg examples nor for Pink apps!

Even with pink website is something not in order. Still if you are willing to build it, and it is worth, try to clone the software with mercurial

hg clone https://pinkhq.com/hg/pink <https://pinkhq.com/hg/pink> (for Windows I don't know a command)

There is a makemgw.bat for Windows, still some effort!

**Comment by karo11** [comment]
Unluckily not, neither for CImg examples nor for Pink apps!

Even with pink website is something not in order. Still if you are willing to build it, and it is worth, try to clone the software with mercurial

hg clone https://pinkhq.com/hg/pink <https://pinkhq.com/hg/pink> (for Windows I don't know a command)

There is a makemgw.bat for Windows, still some effort!

I have found the documentation of Pink apps under http://perso.esiee.fr/~coupriem/Pink/doc/html/files.html!
