### ISSUE TITLE
Move .gmicrc config to $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by mrbnny** [dtschump/gmic-community#5]
Please make gmic adhere to XDG user directory standards. (i.e. do not save configs to $HOME/.gmicrc but rather to $XDG_CONFG_HOME/.gmicrc)

From freedesktop.org:

$XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

Source: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by dtschump** [comment]
That's a good idea indeed. 
My latest commit will fix this issue : https://github.com/dtschump/gmic/commit/76e558c875ba8ab11187050923ea9018af0f9965

Thanks for the suggestion.

**Comment by mrbnny** [comment]
Thanks for doing this, and for the project in its entirety.
