### ISSUE TITLE
G'Mic crashes....

### ISSUE THREAD

**Issue by Steve-Wellens** [dtschump/gmic-community#51]
Gimp 2.8.16
G'MIC 1.7.2

1) Open an Image
2) Start G'MIC
3) Chose filter Artistic, Dream Smoothing (note, the same problem occurs on other filters).
4) Click Apply...do not close G'MIC
5) In Gimp, select File, Revert...
6)  G'MIC crashes....see attached image.
![error](https://cloud.githubusercontent.com/assets/11036606/15877395/16a03d8c-2cd9-11e6-8f67-773494cf1ada.png)

**Comment by dtschump** [comment]
Hello Steve.
Does it happen only with one particular image, or does it happen every time ?
Of course, this works here, on my GIMP 2.8.16 and G'MIC 1.7.2, so there is probably something different either in your installation, or with the data you are trying to process. We must find out where this difference is. Any idea or additional information about your install and your image data ?

**Comment by Steve-Wellens** [comment]
It happens on other images.
One extra thing I found, if it doesn't crash right away, click Reset on G'MIC.

1) Open an Image
2) Start G'MIC
3) Chose filter Artistic, Dream Smoothing (note, the same problem occurs on other filters).
4) Click Apply...do not close G'MIC
5) In Gimp, select File, Revert...
**5.5) Click Reset in G'MIC**
6) G'MIC crashes....see attached image.

I can't think of anything else weird at this time.  I try to use things 'out of the box' to avoid weirdness and edge cases.

**Comment by dtschump** [comment]
Should be fixed now.
