### ISSUE TITLE
Artifacs appear when using Inpaint [transport-diffusion]

### ISSUE THREAD

**Issue by Anthony-Gaudino** [dtschump/gmic-community#53]
I was playing with the `Inpaint [transport-diffusion]` filter on GIMP and I noticed that for very small masked areas it can create artifacts where some pixels will turn into strong yellow, green, red or blue color.

This happens when using `Edge Oriented` regularization and high values for `Regularization Iterations` setting.

I have a very minimal example, it's just a 4x4 image that when processed creates two yellow pixels next to the beige pixel. I used these settings on the filter:
```
* Smoothness:                0
* Regularization:            Edge Oriented
* Regularization iterations: 100
* Mask color:                #FF0000
* Mask dilation:             0
```

I tested this on both Windows and Linux 64bit with versions 1.7.2 and 1.7.3.

EXAMPLE -> ![inpaint_bug](https://cloud.githubusercontent.com/assets/2439728/16168581/c0a60c74-34e2-11e6-902f-296caed56a62.png) <- EXAMPLE

**Comment by dtschump** [comment]
Ah that's interesting. Instead of the resulting image, could you provide the input image ?
I didn't succeed to reproducing the bug, but I think I may have an idea why this happens.
Thanks.

**Comment by dtschump** [comment]
OK I've done a small modification in the filter sources.
The issue should be gone now (after a filter refresh).

**Comment by Anthony-Gaudino** [comment]
The example I provided is not the resulting image, it's the input image.

I updated the plugin, but I'm not sure if the changes you made didn't fix it or the updates fail, I updated as usual, by clicking on the update button, and I have the `gimp_update173.gmic` file but the results are the same. I also tried downloading and installing the plugin again.

Bellow is the result image generated by the inpaint with the settings I provided before, it creates two yellow (#ffff00) pixels around the beige pixel.

RESULT -> ![inpaint_bug_2](https://cloud.githubusercontent.com/assets/2439728/16171353/22027c22-3543-11e6-9520-4f3927878135.png) <- RESULT

**Comment by dtschump** [comment]
Hello Anthony, Thanks for the explanations.
I can indeed confirm the issue here, even with the updated filters.
I'm working on a fix :)

**Comment by dtschump** [comment]
Ok this should be fixed now. Try updating your filters once again.
There is only a small problem with the preview that is not accurate, but this can't be fixed easily.
Applying the filter should give you a correct result anyway.

**Comment by Anthony-Gaudino** [comment]
Thank you.

The problem is solved.
