### ISSUE TITLE
G'MIC 1.7.2 fails while updating definition file.

### ISSUE THREAD

**Issue by tonurics** [dtschump/gmic-community#57]
Version: 1.7.2
OS: Arch Linux 64bit

gmic -v +10 -up
> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Set verbosity level to 10.
> [gmic]-0./ Update commands from the latest definition file on the G'MIC server.
> [gmic]-0./up/_update/ Decrement verbosity level (set to 9).
> [gmic]-0./up/_update/ Set local variable out='/home/jason/.config/gmic/cli_update172.gmic'.
> [gmic]-0./up/_update/*local/ Start '-local..-endlocal' block, with selected image [].
> [gmic]-0./up/_update/*local/ Input file 'http://gmic.eu/cli_update172.gmic' at position 0
> [gmic]-0./up/_update/*local/ *** Error *** [instance(0,0,(nil))] CImgList<float>::load_cimg(): CImg header not found in file '/tmp/QJpa3fFW.cimgz'.
> [gmic]-0./up/_update/*local/ Reach '-onfail' block.
> [gmic]-0./up/_update/*local/ Increment verbosity level (set to 10).
> [gmic]-0./up/ *** Error *** Command '-update' : Unreachable update file.

**Comment by dtschump** [comment]
Update file : http://gmic.eu/cli_update172.gmic exists and should be reachable (click on the link to check). So, there may be different reasons why the update doesn't work as expected : 

- Maybe the gmic server has been down for a short time, just when you tried to update.
- Or, `gmic` cannot retrieve the file from a URL. `gmic` basically uses the `libcurl` library to retrieve files from network, so maybe a problem with `libcurl` ? or with a firewall with strict rules ?

**Comment by tonurics** [comment]
The URL being unreachable was my first thought as well. But there were no issues accessing it via my browser [which I tried right after the error occurred]. I don't have anything funky with my firewall and for due process I just downloaded the file via the curl CLI without any issues.

Since creating this ticket: I've also repeated this error on another machine; where the update command worked previously [~4 months ago].

The error output complains about "CImg header not found" which seems out of place, assuming it's referring to the C++ library and I'm not using G'MIC on an image. [I'm just a G'MIC user. Please forgive my ignorance of the code base, if I'm in-fact pointing at a red herring.]

Thoughts? Is there perhaps a place I can manually put the definition file?

P.S. On a personal note: G'MIC is awesome, thanks for your work on it!

**Comment by dtschump** [comment]
Ah OK , that is strange indeed.
The place to put the update file should be `$HOME/.config/gmic/` (or `%APPDATA/gmic/` on Windows).
If you have some time to test with the latest available version (currently `1.7.5_pre`), I would be interested as well :)
Thanks for reporting.

**Comment by tonurics** [comment]
The 1.7.5_pre version works correctly! I also noted that the console output still makes reference to loading an image; but this time it saves an output "image" to the update file path.

I think the problem lies with the update files on the server. I noticed that the file fetched by 1.7.5_pre [ http://gmic.eu/update175.gmic ] is a binary file with an encoding header, while the 1.7.2 file [ http://gmic.eu/cli_update172.gmic ] is just a text file containing source code.
