### ISSUE TITLE
extract foreground crashing G'mic for Gimp plugin

### ISSUE THREAD

**Issue by narayaan** [dtschump/gmic-community#59]
I was playing with the extract foreground in the G'mic for Gimp filter and noticed that this app was crashing a lot while using a lot of markers.

I don't really noknow if this is an issue of G'mic or Gimp, but these are the error messages I get (unfortunately in Dutch..)

![extract foreground](https://cloud.githubusercontent.com/assets/12802235/19400362/2c402bce-9256-11e6-81ac-5c0ca8300a82.png)

Using Gimp 2.8.18 an G'mic 1.7.7

**Comment by narayaan** [comment]
Tried again today with 1.7.8 and updated filters. Again an error message:
![probleem gmic](https://cloud.githubusercontent.com/assets/12802235/19621202/fb1c1386-988c-11e6-832a-e2c4b9e5f1b7.png)

I retested this some times, and this only happens when I use a lot of marker points. While using just a few marker points there doesn't seem to be a problem.

**Comment by narayaan** [comment]
These are the settings I'm using.

![instellingen](https://cloud.githubusercontent.com/assets/12802235/19621274/8e07b7b2-988e-11e6-91be-dadeb1e6f5ea.png)

**Comment by dtschump** [comment]
Should be fixed now.
