### ISSUE TITLE
Current GMIC version doesn't work on Ubuntu 16.10

### ISSUE THREAD

**Issue by terzag** [dtschump/gmic-community#61]
Using Ubuntu 16.10 64-bit with Gimp 2.8.18. Installing GMIC from the repos works fine but the version is outdated (not sure of the exact one: the package version seems to be 1.6.8.3 while the release notes in the plugin show 1.7.0).

Downloading the current version (not sure if it's 1.7.8 or 1.7.9_pre) from the website and putting it in ~/.gimp-2.8/plug-ins doesn't work: GMIC doesn't appear in GIMP's Filters menu anymore. It used to work with a previous version, so I'm sure that I put the file in the right place.

**Comment by dtschump** [comment]
Hi. Thanks for reporting.
I guess this is related to a dynamic library needed by the plug-in binary which is not available anymore in latest versions of Ubuntu.
Could you tell us what:

    $ ldd ~/.gimp-2.8/plug-ins/gmic_gimp

returns ? Any 'not found' library ?

**Comment by terzag** [comment]
Your're right, it's libpng:

`libpng12.so.0 => not found`

I have the libpng16-16 (only version available) package already installed with the following:

```
/usr/lib/i386-linux-gnu/libpng16.so.16
/usr/lib/i386-linux-gnu/libpng16.so.16.25.0
/usr/lib/x86_64-linux-gnu/libpng.so
/usr/lib/x86_64-linux-gnu/libpng16.so
/usr/lib/x86_64-linux-gnu/libpng16.so.16
/usr/lib/x86_64-linux-gnu/libpng16.so.16.25.0
```

Doing a symlink as libpng12.so.0 doesn't seem to work.

**Comment by dtschump** [comment]
OK. I've installed Ubuntu 16_10 as a virtual machine, and tried to compile the plug-in, following the instruction from the page : http://gmic.eu/download.shtml#source
It works great. Maybe you should try this method instead.
I'll probably try to build a G'MIC .deb package for Ubuntu 16.10 as well, and put it on the download page, but this may take a bit of time :)

**Comment by terzag** [comment]
Thanks, I'll try to compile it.

**Comment by dtschump** [comment]
I've been able to generate new download files specifically for Ubuntu 16.10,
available from here : http://gmic.eu/download.shtml, and here : http://gmic.eu/gimp.shtml
If this can help others.. :)

**Comment by dtschump** [comment]
I think this issue can be closed, as I've added new binaries specifically for Ubuntu 16.10 on the G'MIC web site.
