### ISSUE TITLE
"Colors to layers" only creates two layers

### ISSUE THREAD

**Issue by victorvde** [dtschump/gmic-community#62]
The title really says it all, but for completeness...

Using the GIMP plugin on Windows 10 (GIMP 2.8.18, G'MIC plugin fully updated and filters updated):

1. Open an image, for example http://flaglane.com/download/norwegian-flag/norwegian-flag-large.png
2. Use the "Colors to layers" filter with default settings

Expected results:
At least three layers are created

Observed result:
Only two layers are created

Changing the image or changing the settings has no effect.

**Comment by dtschump** [comment]
You are right. I'll try to understand what happens.

**Comment by dtschump** [comment]
OK, should be fixed now (after a filter refresh).
Could you test and tell me ? Thanks for your report !

**Comment by victorvde** [comment]
Yes, it works for me now.

Thank you for the quick fix.
