### ISSUE TITLE
Polish translation of G'MIC

### ISSUE THREAD

**Issue by m4sk1n** [dtschump/gmic-community#63]
Hi! How to contribute to Polish translation of G'MIC? I don't understand it.

**Comment by dtschump** [comment]
Hello.
The translation of the interface in Polish should be already done, here : https://github.com/dtschump/gmic/blob/master/src/gmic_gimp.cpp#L840

If you want to translate the text of the filters, then look at this file : 
https://github.com/dtschump/gmic-community/blob/master/include/tou_omiya.gmic

It is how the japanese version is done. It should give you the idea on how to do it in another language.

**Comment by m4sk1n** [comment]
@dtschump
That's what I was going to do. But can I get any example in any other language with Latin alphabet?

**Comment by dtschump** [comment]
I can do one example in French for instance. But not before next week unfortunately.
