### ISSUE TITLE
Poor results with Inpainting

### ISSUE THREAD

**Issue by knottb** [dtschump/gmic-community#65]
HI,

I am trying to use G'MIC to perform inpainting using the command-line. I'd love to be able to get results like in https://github.com/dtschump/gmic-community/wiki/G'MIC-Inpainting-Results but I've tried various settings and am having trouble getting anything passable.

My best result so far has been using the command:

`gmic input.jpg mask.png  -inpaint[0] [1],5,15,2,16,0,0.05,10,1,0 -remove[-1] -o out.jpg`

I am wondering if there is something I am not realizing about the command line tool that is causing the issue.

Here are the test images for the input, mask, and resulting output.

Any help would be greatly appreciated. Thanks.

![tree](https://cloud.githubusercontent.com/assets/19143914/21236236/394ece40-c2c8-11e6-9997-83abd1e48c57.jpg)
![mask](https://cloud.githubusercontent.com/assets/19143914/21236238/3e5f207e-c2c8-11e6-8d7e-93200e1fd403.png)
![out](https://cloud.githubusercontent.com/assets/19143914/21236250/439880e4-c2c8-11e6-9f5d-22ea3ce16b22.jpg)

**Comment by narayaan** [comment]
Hi, you might have better luck asking your question on the pixls.us forums:https://discuss.pixls.us/c/software/gmic
