### ISSUE TITLE
Many GMIC filters crashing on gimp 2.9.5 (commit 36ebe03)

### ISSUE THREAD

**Issue by chconnor** [dtschump/gmic-community#67]
Hello -- I recently updated GIMP from Otto Meier's repo to 2.9.5 (gimp commit 36ebe03) and can't seem to get most GMIC filters to work anymore -- many of them crash (e.g. most of those in the "Details" submenu). This is on Kubuntu 16.10.

I upgraded gmic to 2.0.0 from gmic.eu (via .deb install) and the problem remains. Tried with a fresh .config/GIMP and I get the same thing. If I run gimp --verbose I see the prompt for a stack trace but "S" generates nothing (perhaps I need to install symbols or something).

Hopefully it's appropriate to post this here -- let me know if not, or if I can provide any other information.

Thanks!

**Comment by dtschump** [comment]
Thanks for notifying us about this issue.
I'll try to update GIMP 2.9 as well from the PPA to see what happens (I'm on Lubuntu 16.04), and if I can do something. When you say 'it crashes', what kind of crash ? do you get an error message somewhere, or does the plug-in segfault ?

**Comment by chconnor** [comment]
Thanks David! -- when I run gimp normally, make a new image, tun GMIC (now "GMIC - 2.0.0"), select Details -> Freaky Details, gimp's error dockable says:

```
Plug-in crashed: "gmic_gimp2"
(/usr/lib/gimp/2.0/plug-ins/gmic_gimp2)

The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side.

```
If I run gimp --verbose, and do the same, it pauses and I see:

```
/usr/lib/gimp/2.0/plug-ins/gmic_gimp2: fatal error: Segmentation fault
/usr/lib/gimp/2.0/plug-ins/gmic_gimp2 (pid:4260): [E]xit, [H]alt, show [S]tack trace or [P]roceed: 
```

"S" does nothing, "E" continues as before.

There is this error just before, but it is also logged when successful choosing of a GMIC option, so I'm not sure if it's relevant:

```
(gmic:4791): LibGimp-CRITICAL **: gimp_zoom_preview_set_drawable_id: assertion 'preview->priv->drawable_ID < 1' failed

(gmic:4791): LibGimp-CRITICAL **: gimp_zoom_preview_set_drawable_id: assertion 'preview->priv->drawable_ID < 1' failed
```

I was trying to find an example of a GMIC option that worked, but now I can't seem to find one. I'm in a hurry right now or I'd look more. Let me know if it'd be useful and I'll try more. (Of course it's possible it was random that it sometimes worked before.)

**Comment by chconnor** [comment]
Another data point, in case it's helpful for narrowing down the issue: I tried to use this AppImage from pixls.us: gimp-2.9.5-20170103.glibc2.15-x86_64.AppImage

That's gimp commit 8111ad6; gmic 1.8.0. At first it seemed to work, but with a free select region I brought up gmic, which was preselected to freaky details, and it crashed in the same way. It did seem more stable though: before the crash, I ran a few freaky details passes successfully.

**Comment by chconnor** [comment]
Getting strange... I was trying to go back in time until it worked, but I get the same thing with gimp-2.9.5-20161128 and gimp-2.9.5-20160916... that last one is earlier in gimp/gmic versions than my last successful install (which, as mentioned, was from Otto's edge repo, and which was using gmic 1.8.0, IIRC). So I'm wondering if something on my system is interacting and causing the breakage? (I'd have thought the AppImage versions would include all their own libraries, though.)

Any ideas? Perhaps I should install some debug symbols and generate a trace somehow? I'm handy on the CLI if you wanted to guide me. (Assuming you can't reproduce it yourself.)

**Comment by chconnor** [comment]
More:

pixls.us 2.9.5-20170103 AppImage works fine AFAICT on a separate Lubuntu 16.10 install i have.

Partha's portable Windows build: http://partha.com/downloads/Gimp-2.9.5-std-64bit-portable.exe
...crashes when I try to run GMIC (on Win 8.1 x64) with the following error:

`Unhandled exception at 0x0000000063ABAD13 (libgimpwidgets-2.0-0.dll) in gmic_gimp.exe: 0xC0000005: Access violation reading location 0x000000000A853430.
`

**Comment by dtschump** [comment]
Thanks for all your tests !
I have no clues what is going on right now. I'll try to test the PPA by myself when I'll have some time.
Do you get the same errors when you use the plug-in binaries provided on the G'MIC web site 
(http://gmic.eu/gimp.shtml) ? Just curious :)

**Comment by chconnor** [comment]
Like the files here?: http://gmic.eu/files/prerelease/

Yeah -- the first thing I tried was to install the 2.0.0 prerelease (via .deb from that site) in my normal Otto Meier edge gimp -- same issue.

I'm going to install a virgin Kubuntu 16.10 and see if I can reproduce there.

(FYI I've also tried with compositing off and with an older kernel, just for the heck of it. :-) No luck.)

**Comment by dtschump** [comment]
Just tested with the otto PPA, here on Lubuntu 16.04, and all is working well :(
(http://i.imgur.com/zBgWX9p.png)
If you have more clues about when this issue arises, please let us know !

**Comment by chconnor** [comment]
Thorsten Stettin (who I understand is the Otto Meier gimp repo maintainer, as I'm sure you know) was apparently able to reproduce and he's looking in to it:

https://mail.gnome.org/archives/gimp-user-list/2017-January/msg00133.html

Thanks! Sorry to trouble you -- seems like it might have been a distribution issue.

**Comment by chconnor** [comment]
...although as soon as I write that I wonder "why didn't any of the other versions work either?"... so I'll let you know how it turns out...

**Comment by rich2005** [comment]
Using a Kubuntu 16.04 VM and last update of Gimp 2.9.5 'gimp-edge'

Gmic fails to compile with this but was successful with the previous ''gimp-edge'

terminal output attached
[bad.txt](https://github.com/dtschump/gmic-community/files/715035/bad.txt)


If desperate, my appimage of the earlier Gimp 2.9.5 that works with gmic 
see  http://www.gimp-forum.net/Thread-Portable-Gimp-2-9-5-for-linux?pid=581#pid581

This is the one, I am using at the moment.

To avoid mixing with other appimages it is named GIMP295.bin, 64 bit runs from your home partition, uses the regular gimp 2.9.5 profile. Usual guarantee, there is none.

**Comment by chconnor** [comment]
Thanks, Rich, that's working for me!

**Comment by chconnor** [comment]
Latest gimp from otto-kesselgulasch repo seems to work fine with gmic.
Thanks for the attention to this!
