### ISSUE TITLE
GIT version doesn't compile / segfault with recent GIMP (GIT-version)

### ISSUE THREAD

**Issue by HJarausch** [dtschump/gmic-community#68]
Hi, since GMIC doesn't compile with recent GIMP I have applied some patches - see below.
Then it compiles but segfaults.

Many thanks for looking at my patches and the reason why it segfaults,
Helmut

/usr/lib64/gimp/2.0/plug-ins/gmic_gimp2: fatal error: Segmentation fault
/usr/lib64/gimp/2.0/plug-ins/gmic_gimp2 (pid:14530): [E]xit, [H]alt, show [S]tack trace or [P]roceed: S
#0  0x00007ffff381708a in waitpid () from /lib64/libpthread.so.0
#1  0x00007ffff414e303 in g_on_error_stack_trace ()
#2  0x00007ffff414e46c in g_on_error_query () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff74e7073 in gimp_plugin_sigfatal_handler ()
#4  <signal handler called>
#5  0x00007ffff1c27526 in strlen () from /lib64/libc.so.6
#6  0x00007ffff1becd27 in printf_positional () from /lib64/libc.so.6
#7  0x00007ffff1bed99f in vfprintf () from /lib64/libc.so.6
#8  0x00007ffff1c9e71d in __vsnprintf_chk () from /lib64/libc.so.6
#9  0x00007ffff1c9e678 in __snprintf_chk () from /lib64/libc.so.6
#10 0x0000000000464802 in process_preview() ()
#11 0x00007ffff4454172 in g_closure_invoke ()
#12 0x00007ffff44660ca in signal_emit_unlocked_R ()
#13 0x00007ffff446ec4d in g_signal_emit_valist ()
#14 0x00007ffff446f0a2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#15 0x00007ffff796d05f in gimp_preview_invalidate_now ()
#16 0x00007ffff4179a13 in g_timeout_dispatch ()
#17 0x00007ffff4178ef9 in g_main_context_dispatch ()
#18 0x00007ffff4179298 in g_main_context_iterate.isra ()
#19 0x00007ffff4179612 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff58720af in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#21 0x000000000046d70d in gmic_main() ()
#22 0x000000000046dad2 in gmic_run(char const*, int, _GimpParam const*, int*, _GimpParam**) ()
#23 0x00007ffff74e795c in gimp_main () from /usr/lib64/libgimp-2.0.so.0
#24 0x00007ffff1bc6211 in __libc_start_main () from /lib64/libc.so.6
#25 0x000000000043974a in _start ()
/usr/lib64/gimp/2.0/plug-ins/gmic_gimp2 (pid:14530): [E]xit, [H]alt, show [S]tack trace or [P]roceed: E

[NewGimp_patch.txt](https://github.com/dtschump/gmic-community/files/727447/NewGimp_patch.txt)

**Comment by dtschump** [comment]
Hi Helmut,
Unfortuantely, I cannot help much.
1. I'm not able to compile GIMP fro git, I don't know why but I got missing dependencies.
2. There are no docs on the API changes from the GIMP side, so I guess only the GIMP developers could tell us what is going on !

If someone else has a clue about that, he is more than welcome :)

**Comment by HJarausch** [comment]
Thanks David,
I've just asked for help on the Gimp developer list.
The other way round: perhaps I can help you compiling Gimp(GIT).
I am on Gentoo, and I can see you my "ebuild" file which shows all dependencies and patches.

**Comment by dtschump** [comment]
Ah thanks. According to this page : 
http://www.mail-archive.com/gimp-developer-list%40gnome.org/msg07722.html
It seems things should be better now.
Any feedback appreciated !
