### ISSUE TITLE
Freaky Details broken on latest GIMP 2.9.5?

### ISSUE THREAD

**Issue by chconnor** [dtschump/gmic-community#70]
Hello - on GIMP 2.9.5 (commit 6aaf66700, from otto-kesselgulasch) on Kubuntu 16.10 with GMIC 2.0.0, effect Details -> Freaky details seems to be broken.

The preview window says:

    *** Error in ./fx_freaky_details_preview/gui_split_preview/*repeat/(...)/mix_rgb/mix_channels/*repeat/*local/

    *** Unknown command or filename '-m *' (did you mean '-m'?).

Running the filter generates a dialog with the same error.

Any thoughts? Thanks!

**Comment by dtschump** [comment]
Recently in G'MIC 2.0.0_pre, the command `-**` has been replaced by `-m*`, and the filter update as been updated consequently. I believe that if you run an older preversion of of 2.0.0_pre (as probably the one in otto's PPA), you'll get this kind of error yes.
Try updating your plug-in binary from : http://gmic.eu/files/prerelease

**Comment by chconnor** [comment]
Thank you very much - I will try that!

And I will take the issue up with the ppa maintainer. Much obliged.
