### ISSUE TITLE
Libpng15-15.dll is missing for G'mic with GIMP 2.8.20

### ISSUE THREAD

**Issue by motorsep** [dtschump/gmic-community#72]
Libpng15-15.dll is missing for G'mic with GIMP 2.8.20

Initially I thought it was GIMP's issue, but actually it's gmic's:

https://www.youtube.com/watch?v=cQBVeBbtKE0

I also had this issue with previous installs of GIMP for Windows.

Running Windows 10 64bit, GIMP 2.8.20 for Windows.

**Comment by dtschump** [comment]
Thanks for reporting.
Which version of G'MIC did you try to install. Is it the latest stable (*1.7.9*), or the latest pre-release (*2.0.0_pre*) ?
Thanks.

**Comment by motorsep** [comment]
I couldn't tell, because it wouldn't be available in GIMP. I just installed 1.7.9 and the issue is gone. Thanks
