### ISSUE TITLE
Error in gimp_colorize_interactive

### ISSUE THREAD

**Issue by nishlumi** [dtschump/gmic-community#74]
(Problem)
I use G'MIC filter "colorize interactive" in GIMP, occured the error. (Please see attached screen shot)

![win8cap0088](https://cloud.githubusercontent.com/assets/7064488/25069480/cfec065c-22bc-11e7-9108-5ec2bd718420.png)

(Environment)
Windows 10 64bit
GIMP 2.8.20
G'MIC 1.7.9

**Comment by dtschump** [comment]
I'm currently on vacations. I'll check this when I return. Thanks for your report.
