### ISSUE TITLE
segfault on linux GIMP plugin, on XCF but not PNG

### ISSUE THREAD

**Issue by chconnor** [dtschump/gmic-community#75]
I've been using the otto kesselgulasch repo version of GIMP 2.9.5, but recent builds aren't working with g'mic. As a result I switched to the latest AppImage from [here](https://pixls.us/files/) -- 

gimp-2.9.5-20170310.glibc2.15-x86_64.AppImage. That's GIMP commit 2224733, and g'mic 2.0.0. This is on Kubuntu 16.10.

The plugin seems to crash on certain xcf files. If I make a brand new image, it's fine. But the attached example for me crashes when trying to run e.g. Freaky Details. From the CLI:

/tmp/.mount_pb1Eh2/usr/lib/gimp/2.0/plug-ins/gmic_gimp_gtk: fatal error: Segmentation fault

If I export the image to png (same precision) and open that file, it works fine.

[example.zip](https://github.com/dtschump/gmic-community/files/931893/example.zip)

Let me know if there's anything else I can provide or test. Thanks!

**Comment by dtschump** [comment]
Hello. Thanks for reporting. I confirm the bug, I've been able to reproduce it on my machine.
I'll try to understand what is going on.

**Comment by dtschump** [comment]
Patch https://github.com/dtschump/gmic/commit/8d0af5e113c9438fcbe6eb70faaf28e8bfb280cd fixes the issue for me.
Thanks again for your report !

**Comment by chconnor** [comment]
Awesome, thanks for looking at it and fixing it!
