### ISSUE TITLE
gimp plugin segfault on repeated invocation

### ISSUE THREAD

**Issue by chconnor** [dtschump/gmic-community#76]
Hello -- using the [latest AppImage](https://pixls.us/files/gimp-2.9.5-20170310.glibc2.15-x86_64.AppImage) from pixls.us (commit 2224733), I'm getting a crash when running the g'mic plugin.

If I make a new 4000x4000 8bit RGB image and run default Details -> Sharpen [unsharp mask] (output to new layer, in case that matters), it appears to work fine. If I open g'mic subsequent times, it crashes. CLI doesn't show anything interesting, except possibly:

(gmic:27725): GLib-CRITICAL **: Source ID 93 was not found when attempting to remove it

I note that trying this on a 200x200 image did not cause the crash. I noticed this issue when doing some photo editing. I have to run G'MIC once, save the file, close gimp, open it again, and then I can run a second G'MIC invocation.

Happy to provide anything else if it would be useful!

**Comment by dtschump** [comment]
Hello @chconnor , thanks for your report.
I don't know what happens, but what I can say is that the GTK-version of the G'MIC plug-in should now be considered as obsolete, and no longer maintained.
We are putting all our efforts on the Qt-version of the plug-in now, available here : https://github.com/c-koi/gmic-qt

**Comment by chconnor** [comment]
Thanks -- I will not report bugs against the GTK version anymore.
