### ISSUE TITLE
improvement proposal -information popups

### ISSUE THREAD

**Issue by narayaan** [dtschump/gmic-community#77]
When using a filter, there are a lot of adjustable options that are not allways straightforward, especially for non native speakers .

It would be nice to have a pop-up appearing when hovering about a certain keyword with information about what changing this parameter exactly does.

EG: In Foreground (interactive) we have the option to "dilate". It would be nice to have ome information about what exactly will happen when using this slider.

**Comment by dtschump** [comment]
Actually, more than popups, a filter should always have a comprehensive documentation, with an explanation of all the parameters. Only a few filters have such a page attached to them.
G'MIC lacks documentation, definitely.

Considering the number of available filters, we indeed need contributors to write documentation pages ;)
