### ISSUE TITLE
libunistring-2.dll error

### ISSUE THREAD

**Issue by rpabas** [dtschump/gmic-community#80]
Please help. libunistring-2.dll cannot be found

**Comment by E-Gwen** [comment]
Bonjour,

J'ai installé le greffon G'MIC 2.0 pour Windows XP, et j'ai le message d'erreur suivant au lancement de Gimp 2.8.22 : 
"Cette application n'a pas pu démarrer car libunistring-2.dll est introuvable. La réinstallation de cette application peut corriger ce problème."

Du coup, une fois GIMP 2.8.22 lancé, G'MIC n'apparaît point dans les greffons.

Dans ces conditions, il est difficile de s'en servir.

E-Gwen.

**Comment by E-Gwen** [comment]
La réinstallation de l'application ne corrige pas le problème.

On obtient le même message d'erreur.

Bien à vous.

**Comment by sylale** [comment]
Bonjour,

Si vous êtes sous Windows 64 bits, vous pouvez tester cette version portable sans désinstaller ou ré-installer votre version actuelle de Gimp.

http://www.aljacom.com/~gimp/portables.html

English :
https://translate.google.com/translate?sl=fr&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=http%3A%2F%2Fwww.aljacom.com%2F~gimp%2Fportables.html&edit-text=&act=url

Bonne chance!

**Comment by E-Gwen** [comment]
Merci, mais j'ai précisé que je suis sous Windows XP, et donc implicitement que j'utilise la version 32 bits (La version 64 bits de XP étant anecdotique, et désuète depuis longtemps).

Bon, j'ai téléchargé le fichier zip gmic_cli_win32.zip du 2 juin 2017 (ici : http://gmic.eu/files/prerelease/), l'ai décompressé, ai récupéré la bibliotèque dynamique libunistring-2.dll, et l'ai copié dans C:\Documents and Settings\Gwen\.gimp-2.8\plug-ins.

J'ai relancé GIMP 2.8.22.

Je n'ai plus de message d'erreur. Par contre, dans la fenêtre "Filtres", G'MIC-GTK apparait en grisé, et reste donc inaccessible.

Une idée pour me permettre d'utiliser ce greffon ?

E-Gwen.

**Comment by E-Gwen** [comment]
En fait, il suffit d'ouvrir une photo pour que le filtre G'MIC-GTK puisse être utilisé.

De cette manière, il est donc possible d'utiliser G"MIC 2.0.1pre avec GIMP 2.8.22 sous Windows XP 32 bits.

Pour nos amis anglo-saxxons : 

How to proceed : 

Go to http://gmic.eu/files/prerelease/)

Download the gmic_cli_win32 file.

Extract it and paste the libunistring-2.dll library to  C:\Documents and Settings\your-own-session.gimp-2.8\plug-ins.

Launch GIMP, open a picture, go to "Filters", and enjoy G'MIC 2 !

E-Gwen.

**Comment by dtschump** [comment]
Bonjour @E-Gwen ,
Le plug-in Qt est effectivement connu pour ne pas fonctionner sur les vieux systèmes Windows XP, donc je pense qu'à moins de bidouiller comme un fou, il ne faut pas trop espérer le faire marcher.
Le plug-in GTK doit effectivement fonctionner. Le problème de .dll manquants pour les plug-in est réccurent sous Windows (cela dépend bcp de la version de GIMP utilisée), et les développeurs de GIMP en sont conscient et vont proposer dans la prochaine version GIMP 2.10 un moyen de bien isoler les plug-ins et leurs DLLs pour que tout rentre dans l'ordre.
