### ISSUE TITLE
Extract foreground [interactive] result in offest layers with G'mic 0.1.7 in Krita 3.1.4

### ISSUE THREAD

**Issue by nylnook** [dtschump/gmic-community#82]
This may be solved with Gmic 2, but for some pictures (including this one: https://commons.wikimedia.org/wiki/Earth#/media/File:BlueMarble-2001-2002.jpg), using the extract foreground [interactive] filter of G'mic in Krita may result in offest layers.
Using the background dots (red ones) instead of the foreground dots (green ones) for the foreground usually workaround the issue. 

Here are some screenshots to be more clear: 
![capture d ecran de 2017-06-07 13-50-04](https://user-images.githubusercontent.com/456282/26877249-96b9b154-4b89-11e7-878d-f7d88c6b2229.png)

![capture d ecran de 2017-06-07 13-50-20](https://user-images.githubusercontent.com/456282/26877266-a0d0e8b0-4b89-11e7-9144-19e68c3c0767.png)

![capture d ecran de 2017-06-07 13-50-26](https://user-images.githubusercontent.com/456282/26877271-a5f834f6-4b89-11e7-9bc0-2ec815f2e5e9.png)

Depending on the ratio of the picture, the bug seem to occur or not. It doesn't occur in Gimp.

By the way, congrats for the 2.0 release !

**Comment by dtschump** [comment]
I'm sorry but I think this bug should be notified to the Krita developers instead.
We are not the authors of the G'MIC plug-in for Krita, and have therefore no control on its source code !

**Comment by nylnook** [comment]
Sorry David, I never know if it depends on Krita or on G'mic developers ;)

Reported here : https://bugs.kde.org/show_bug.cgi?id=381204

Thanks again !
