### ISSUE TITLE
Error at startup of GIMP with G'MIC 2.0

### ISSUE THREAD

**Issue by micter59** [dtschump/gmic-community#83]
Hello !

I've installed the 2.0 version (qt) of G'MIC, with the Windows Installer (x64).
GIMP's version is 2.8.20.
Installation seems ok, but everytime GIMP is starting, there's an error message : "Le point d'entrée de procédure pthread_setname_np est introuvable dans la bibliothèque de liens dynamiques (...) libglib-2.0-0.dll". 
G'MIC doesn't appear in GIMP list of filter :-(

![erreur_lancement_plugin_gmic_x64_2 0](https://user-images.githubusercontent.com/6595295/27002911-e914aa70-4dec-11e7-8fd6-e9f466c9a7ff.png)

Thank's a lot for your work !

Michaël

**Comment by dtschump** [comment]
In case of .dll problems, I would suggest trying to install your plug-in in a custom folder (not the default plug-in folder), then go to GIMP -> Preferences -> Paths -> and add your folder to the plug-in path.
