### ISSUE TITLE
Failed to buid latest git version: error: ‘data_gmic_preview_warning’ was not declared in this scope

### ISSUE THREAD

**Issue by JeanLucCoulon** [dtschump/gmic-community#84]
Hi,

I'm running Debian sid with linux-2.4.11 and git version of gimp.

When I tried to build latest git version, I get the following:
[...]
[ 58%] Building CXX object CMakeFiles/gmic_gimp_gtk.dir/src/gmic_gimp_gtk.cpp.o
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp: In function 'void _gimp_preview_invalidate()':
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp:2286:68: error: 'data_gmic_preview_warning' was not declared in this scope
       CImgList<unsigned char>::get_unserialize(CImg<unsigned char>(data_gmic_preview_warning,
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp:2287:70: error: 'size_data_gmic_preview_warning' was not declared in this scope
                                                                    1,size_data_gmic_preview_warning,1,1,true))[0].
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp: In function 'void create_dialog_gui(bool)':
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp:4216:66: error: 'data_gmic_logo' was not declared in this scope
     CImgList<unsigned char>::get_unserialize(CImg<unsigned char>(data_gmic_logo,1,size_data_gmic_logo,1,1,true))[0].
                                                                  ^~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic_gimp_gtk.cpp:4216:83: error: 'size_data_gmic_logo' was not declared in this scope
     CImgList<unsigned char>::get_unserialize(CImg<unsigned char>(data_gmic_logo,1,size_data_gmic_logo,1,1,true))[0].
                                                                                   ^~~~~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp: In static member function 'static const cimg_library::CImg<char>& gmic::decompress_stdlib()':
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:59: error: 'data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                           ^~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:78: error: 'size_data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                                              ^~~~~~~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp: In static member function 'static const cimg_library::CImg<char>& gmic::decompress_stdlib()':
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:59: error: 'data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                           ^~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:78: error: 'size_data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                                              ^~~~~~~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp: In static member function 'static const cimg_library::CImg<char>& gmic::decompress_stdlib()':
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:59: error: 'data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                           ^~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:78: error: 'size_data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                                              ^~~~~~~~~~~~~~~~~~~~~
CMakeFiles/gmic_gimp_gtk.dir/build.make:86: recipe for target 'CMakeFiles/gmic_gimp_gtk.dir/src/gmic_gimp_gtk.cpp.o' failed
make[2]: *** [CMakeFiles/gmic_gimp_gtk.dir/src/gmic_gimp_gtk.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp: In static member function 'static const cimg_library::CImg<char>& gmic::decompress_stdlib()':
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:59: error: 'data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                           ^~~~~~~~~~~~~~~~
/usr/local/src/gmic/gmic-2.0.1/src/gmic.cpp:2425:78: error: 'size_data_gmic_stdlib' was not declared in this scope
       CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                                              ^~~~~~~~~~~~~~~~~~~~~
CMakeFiles/gmic_gimp_gtk.dir/build.make:62: recipe for target 'CMakeFiles/gmic_gimp_gtk.dir/src/gmic.cpp.o' failed

Regards

Jean-Luc

**Comment by dtschump** [comment]
I'd suggest not to use the CMakeFile from the git version, but go to `gmic/src` and type `make` directly.
There are two required files that are not shipped in the git repo that will be downloaded by the Makefile, so that could make a difference.
