### ISSUE TITLE
Variables commençant par un F majuscule

### ISSUE THREAD

**Issue by sylale** [dtschump/gmic-community#86]
Bonjour,

Il n'est pas possible d'utiliser les variables commençant par un F majuscule, elles donnent une erreur sur G'MIC Gimp QT 2.0.2 Win (compilation officielle + personnelle).
Par exemple 
Zvariable=130
-deform $Zvariable

Merci

**Comment by dtschump** [comment]
Indeed, commit https://github.com/dtschump/gmic/commit/378747cc44f3d954d4d198f7bb57518a8c1aa1ee fixes this issue.
I'll then update the binary packages on the website, with a new pre-release version 2.0.3 today.
Thanks Sylvie!

**Comment by sylale** [comment]
Bonjour,
Merci, la nouvelle version 2.0.3 (compilation Windows personnelle) de G'MIC QT et  G'MIC GIMP QT fonctionne avec les variables commençant par Z.
Je continue à faire quelques tests.
Bonne fin de journée.
