### ISSUE TITLE
custom filter in the G’mic plug-in not showing up

### ISSUE THREAD

**Issue by diramazioni** [dtschump/gmic-community#88]
Hello, 
I've read the [wiki instructions for custom filters](https://github.com/dtschump/gmic-community/wiki/How-to-create-a-custom-filter-in-the-G%E2%80%99mic-plug-in) and I had it working before since years in my ~/.gmic (linux) but now I've updated the gimp-gmic plugin to the latest stable (2.02) and my custom filter doesn't show up anymore.
Something has changed and the wiki is outdated? I'm sure is not a problem with my ~/.gmic since I've started from scratch just to be on the safe side

**Comment by karo11** [comment]
Hi Eli,
I had that too some time ago.

The comments used for the help function (cli) and the gui (gimp) have been changed.

I think instead of #@gmic now #@cli is used and instead of #@gimp now #@gui is used! Have a look into the update file update202.gmic or update203.gmic !

Karsten

**Comment by diramazioni** [comment]
ok now they show up!
Beside the wiki docs also About>Filter design gives a wrong template to start with and the #@gui writting it's almost impossible to read with that font 
![image](https://user-images.githubusercontent.com/682046/29250593-5b13f484-8045-11e7-80a9-c0c24dc72d66.png)

thanks for the quick help!

**Comment by karo11** [comment]
Very good!
I don't know who wrote the wiki but it should be open for correction -> do it!
K.
> Am 13.08.2017 um 16:36 schrieb Eli Spizzichino <notifications@github.com>:
> 
> Beside the wiki docs also About>Filter design gives a wrong template to start with

**Comment by dtschump** [comment]
Wiki should be fixed now, thanks for reporting !

**Comment by diramazioni** [comment]
Aww you beat me on time, but still I made a small correction at the end (-fx_blend)
