### ISSUE TITLE
Can I choose a separate part of 2d convert 3d into a dll file and used in other programs?

### ISSUE THREAD

**Issue by DysonGgy** [dtschump/gmic-community#90]
I want to use C# Call the compiled dll file？ anyone have good idea?

**Comment by dtschump** [comment]
No.
The algorithm is written in the G'MIC scripting language, and thus needs the G'MIC interpreter to run.
It cannot be isolated as a single .dll.

**Comment by tobybear** [comment]
You can however write a C# wrapper that calls either the ANSI-C G'MIC interface or the regular C++ G'MIC sources and put that all in a DLL accessible from C#. 
In any case, be aware of the software license G'MIC is distributed under!

**Comment by dtschump** [comment]
@tobybear is right. But that means also that *all* features of G'MIC will be available, not only the 2d->3d conversion algorithm. This has a small cost in terms of library size (though it keeps a reasonable size).
