### ISSUE TITLE
error using Gmic Qt 

### ISSUE THREAD

**Issue by runtsgal** [dtschump/gmic-community#92]
Hi. I keep getting an error on the colorize interactive filter. I just upgraded to Krita 3.2 and I am using windows 10 64 bit on a wacom cintiq companion. Could you suggest a fix, thanks. Angela.

<img width="738" alt="gmic" src="https://user-images.githubusercontent.com/31249067/29571862-4fbd0c4c-8752-11e7-88d0-c92ff089cdd2.PNG">

**Comment by dtschump** [comment]
Looks like your plug-in has been compiled without the support for X11 display.
Where did you find it ? How did you install it ?

**Comment by runtsgal** [comment]
hi. it came bundled with Krita 3.2

**Comment by dtschump** [comment]
I meant 'GDI32 display', not 'X11 display' (that's for Linux).

If it came bundled with Krita 3.2, then maybe one of the Krita dev could help.
I'll reference your issue in the `gmic-qt` repository:  https://github.com/c-koi/gmic-qt/issues

**Comment by runtsgal** [comment]
Should i have deleted the old krita before getting the new version?

**Comment by runtsgal** [comment]
ok thanks

**Comment by dtschump** [comment]
I've just tried with the Appimage for Linux, and the plug-in allows me to use the interactive displays, so I guess this is a Windows-related issue. I can't do much more for now, but Boud will have surely interesting things to say about it.

**Comment by runtsgal** [comment]
thanks for the quick reply

**Comment by dtschump** [comment]
Apparently, Boud has fixed this today : https://github.com/c-koi/gmic-qt/issues/20
Not sure when it will be available, but that's good to know :)

**Comment by runtsgal** [comment]
Brilliant, many thanks. I'll keep an eye out for the fix.
