### ISSUE TITLE
Modern cinema filter returns error

### ISSUE THREAD

**Issue by kinaflex** [dtschump/gmic-community#94]
When choosing the Modern cinema filter in gimp-gmic, "error parsing filter parameters" is returned. This has been the case since gmic 2.0 and persists as of 2.0.3, on both Windows and Linux builds. Other filters in category Testing > Gentlemanbeggar seem to behave as expected.

**Comment by dtschump** [comment]
Thanks. This should be working now.
I guess anyway I should improve a bit the preview of this filter in the future :)
Thanks for your report.

**Comment by kinaflex** [comment]
Thanks for looking into this! Although I should mention that the effect of this filter seems to be completely different from earlier versions. I will do more testing here as I find time and get back to you.

**Comment by kinaflex** [comment]
Samples of the filter effect in 1.7.9: https://imgur.com/a/sD5EA
Samples of the filter effect in 2.0.x: https://imgur.com/a/cAP9f

As you can see, they are quite dissimilar. I find both behaviors can produce useful results. I do not know which behavior is the intended behavior.
