### ISSUE TITLE
local contrast enhancement often not available

### ISSUE THREAD

**Issue by zarniwhoop73** [dtschump/gmic-community#95]
I only use g'mic for the gimp plugin (I don't have all of the dependencies for g'mic itself), and up until last week I had only been building the gimp_gtk plugin. With 2.0.2, building that for gimp-2.9.{5,6} was fine, but when I went back to a gimp-2.8.22 system I discovered that the local contrast enhancement filter was not listed (these are all on current linuxfromscratch with gcc-7.2).

Last week I had time to explore possible changes, and I found out how to build gimp_qt :  I did that on both gimp-2.8.22 and gimp-2.9.6 but neither of them list Local contrast enhancement among the filters.

For my workflow (merge three different exposure variations of the same raw photo) that is a showstopper. I can't see any obvious error messages in the build log - lots of warnings from gcc, but nothing that looks like an error.

At the moment this appears to a random variation, but I can't even find out if the compiled plugin contains this filter - 'strings' does not appear to show the available filter names.

**Comment by dtschump** [comment]
Hello @zarniwhoop73 ,
This particular filter is defined only in the G'MIC update file, usually located at `$HOME/.config/gmic/updateXXX.gmic` where `XXX` are the 3 digits of the G'MIC version number.
This update file should have been downloaded automatically when G'MIC is run the first time, but for some reasons, it has not been done for you (maybe you have a proxy that filters this kind of downloads?).
What I can suggest is : 
- First, try pushing the 'update filters' button (with the 'Internet' checkbox set), it will try to download the update file.
- If this is not working (and you don't get error messages), that is strange :) In that case, try getting the update file 'manually' from there : http://gmic.eu/update202.gmic , then copy it in the folder `$HOME/.config/gmic/` and that should work.

**Comment by zarniwhoop73** [comment]
Thanks, I didn't realise a lot of the filters were only in the updates file. I recall seeing a message on one first-usage, but it didn't mean a lot to me (I assumed it was something to do with noting that a newer version was available.)  Sorted.
