### ISSUE TITLE
Extract Foreground Interactive UI is incredibly slow

### ISSUE THREAD

**Issue by orbisvicis** [dtschump/gmic-community#98]
G'MIC 1.7.2 + 2.0.5pre170920
Gimp 2.8.22

The interactive preview box is very slow to zoom, on the scale of 5-10 seconds. View resolution doesn't seem to make any difference. Also, panning isn't available (would be nice since zoom is so slow).

**Comment by dtschump** [comment]
Hello @orbisvicis ,
Panning is possible with the middle mouse button (tested here with latest 2.0.5).
I didn't noticed the zooming is very slow, so could you tell me a bit more about your image ? what is the resolution ?
I have also a suggestion : did you try the latest 'Smart coloring' filter available in G'MIC 2.0.0+ ? It should work better than the interactive colorize filter, as described here : https://www.davidrevoy.com/article324/smart-coloring-preview-of-a-new-gmic-filter

**Comment by orbisvicis** [comment]
Hi,
The image I'm working with is 2500x3300 (80MB TIFF). At those dimensions I guess pan is so slow it basically doesn't work. I did test a 640x400 image, and pan/zoom felt snappy.

I don't think "smart coloring" is useful here? as I'm using "extract foreground, interactive" and not "colorize, interactive".

**Comment by orbisvicis** [comment]
```
fx_extract_foreground :
  -if {!$!} -return -endif
  resolution={arg(1+$3,512,1024,2048,0)}
```

This means the view resolutions are fixed sizes, so image size shouldn't matter? So this only applies to the foreground extraction algorithm, and the preview window still displays the full-size image...?

**Comment by dtschump** [comment]
Sorry for the delay, I had troubles with my laptop (and don't have it anymore!).
I've tested the Extract foreground filter here, with G'MIC 2.0.4 and an image with size 3000x4800.
The zoom is indeed a bit slow (but not unusable here!). The pan works smoothly with the middle mouse button, particularly when the zoom factor is high.
Not sure what is happening for you. The interface code is almost the same as the colorization filter, so you might have the same issues with this filter too.

I don't have a lot of time these days to do more tests unfortunately. I'll try to check later, sorry about that.
